// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile_ModeratorInfo_ModeratorFee_FeeType int32

const (
	Profile_ModeratorInfo_ModeratorFee_FixedFee               Profile_ModeratorInfo_ModeratorFee_FeeType = 0
	Profile_ModeratorInfo_ModeratorFee_PercentageFee          Profile_ModeratorInfo_ModeratorFee_FeeType = 1
	Profile_ModeratorInfo_ModeratorFee_FixedPlusPercentageFee Profile_ModeratorInfo_ModeratorFee_FeeType = 2
)

var Profile_ModeratorInfo_ModeratorFee_FeeType_name = map[int32]string{
	0: "FixedFee",
	1: "PercentageFee",
	2: "FixedPlusPercentageFee",
}

var Profile_ModeratorInfo_ModeratorFee_FeeType_value = map[string]int32{
	"FixedFee":               0,
	"PercentageFee":          1,
	"FixedPlusPercentageFee": 2,
}

func (x Profile_ModeratorInfo_ModeratorFee_FeeType) String() string {
	return proto.EnumName(Profile_ModeratorInfo_ModeratorFee_FeeType_name, int32(x))
}

func (Profile_ModeratorInfo_ModeratorFee_FeeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 4, 0, 0}
}

type Listing_Metadata_ContractType int32

const (
	Listing_Metadata_PHYSICAL_GOOD  Listing_Metadata_ContractType = 0
	Listing_Metadata_DIGITAL_GOOD   Listing_Metadata_ContractType = 1
	Listing_Metadata_SERVICE        Listing_Metadata_ContractType = 2
	Listing_Metadata_CLASSIFIED     Listing_Metadata_ContractType = 3
	Listing_Metadata_CRYPTOCURRENCY Listing_Metadata_ContractType = 4
)

var Listing_Metadata_ContractType_name = map[int32]string{
	0: "PHYSICAL_GOOD",
	1: "DIGITAL_GOOD",
	2: "SERVICE",
	3: "CLASSIFIED",
	4: "CRYPTOCURRENCY",
}

var Listing_Metadata_ContractType_value = map[string]int32{
	"PHYSICAL_GOOD":  0,
	"DIGITAL_GOOD":   1,
	"SERVICE":        2,
	"CLASSIFIED":     3,
	"CRYPTOCURRENCY": 4,
}

func (x Listing_Metadata_ContractType) String() string {
	return proto.EnumName(Listing_Metadata_ContractType_name, int32(x))
}

func (Listing_Metadata_ContractType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 0, 0}
}

type Listing_Metadata_Format int32

const (
	Listing_Metadata_FIXED_PRICE  Listing_Metadata_Format = 0
	Listing_Metadata_MARKET_PRICE Listing_Metadata_Format = 1
)

var Listing_Metadata_Format_name = map[int32]string{
	0: "FIXED_PRICE",
	1: "MARKET_PRICE",
}

var Listing_Metadata_Format_value = map[string]int32{
	"FIXED_PRICE":  0,
	"MARKET_PRICE": 1,
}

func (x Listing_Metadata_Format) String() string {
	return proto.EnumName(Listing_Metadata_Format_name, int32(x))
}

func (Listing_Metadata_Format) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 0, 1}
}

type Listing_ShippingOption_ShippingType int32

const (
	Listing_ShippingOption_LOCAL_PICKUP Listing_ShippingOption_ShippingType = 0
	Listing_ShippingOption_FIXED_PRICE  Listing_ShippingOption_ShippingType = 1
)

var Listing_ShippingOption_ShippingType_name = map[int32]string{
	0: "LOCAL_PICKUP",
	1: "FIXED_PRICE",
}

var Listing_ShippingOption_ShippingType_value = map[string]int32{
	"LOCAL_PICKUP": 0,
	"FIXED_PRICE":  1,
}

func (x Listing_ShippingOption_ShippingType) String() string {
	return proto.EnumName(Listing_ShippingOption_ShippingType_name, int32(x))
}

func (Listing_ShippingOption_ShippingType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 2, 0}
}

// RPC MESSAGES
type SubscribeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

type UserData struct {
	// Types that are valid to be assigned to Data:
	//	*UserData_Profile
	//	*UserData_Listing
	Data                 isUserData_Data      `protobuf_oneof:"data"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{1}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

type isUserData_Data interface {
	isUserData_Data()
}

type UserData_Profile struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type UserData_Listing struct {
	Listing *SignedListing `protobuf:"bytes,2,opt,name=listing,proto3,oneof"`
}

func (*UserData_Profile) isUserData_Data() {}

func (*UserData_Listing) isUserData_Data() {}

func (m *UserData) GetData() isUserData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserData) GetProfile() *Profile {
	if x, ok := m.GetData().(*UserData_Profile); ok {
		return x.Profile
	}
	return nil
}

func (m *UserData) GetListing() *SignedListing {
	if x, ok := m.GetData().(*UserData_Listing); ok {
		return x.Listing
	}
	return nil
}

func (m *UserData) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserData_Profile)(nil),
		(*UserData_Listing)(nil),
	}
}

type CrawlNodeRequest struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlNodeRequest) Reset()         { *m = CrawlNodeRequest{} }
func (m *CrawlNodeRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlNodeRequest) ProtoMessage()    {}
func (*CrawlNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{2}
}

func (m *CrawlNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlNodeRequest.Unmarshal(m, b)
}
func (m *CrawlNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlNodeRequest.Marshal(b, m, deterministic)
}
func (m *CrawlNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlNodeRequest.Merge(m, src)
}
func (m *CrawlNodeRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlNodeRequest.Size(m)
}
func (m *CrawlNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlNodeRequest proto.InternalMessageInfo

func (m *CrawlNodeRequest) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type CrawlNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlNodeResponse) Reset()         { *m = CrawlNodeResponse{} }
func (m *CrawlNodeResponse) String() string { return proto.CompactTextString(m) }
func (*CrawlNodeResponse) ProtoMessage()    {}
func (*CrawlNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{3}
}

func (m *CrawlNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlNodeResponse.Unmarshal(m, b)
}
func (m *CrawlNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlNodeResponse.Marshal(b, m, deterministic)
}
func (m *CrawlNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlNodeResponse.Merge(m, src)
}
func (m *CrawlNodeResponse) XXX_Size() int {
	return xxx_messageInfo_CrawlNodeResponse.Size(m)
}
func (m *CrawlNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlNodeResponse proto.InternalMessageInfo

type BanNodeRequest struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BanNodeRequest) Reset()         { *m = BanNodeRequest{} }
func (m *BanNodeRequest) String() string { return proto.CompactTextString(m) }
func (*BanNodeRequest) ProtoMessage()    {}
func (*BanNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{4}
}

func (m *BanNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BanNodeRequest.Unmarshal(m, b)
}
func (m *BanNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BanNodeRequest.Marshal(b, m, deterministic)
}
func (m *BanNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BanNodeRequest.Merge(m, src)
}
func (m *BanNodeRequest) XXX_Size() int {
	return xxx_messageInfo_BanNodeRequest.Size(m)
}
func (m *BanNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BanNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BanNodeRequest proto.InternalMessageInfo

func (m *BanNodeRequest) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type BanNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BanNodeResponse) Reset()         { *m = BanNodeResponse{} }
func (m *BanNodeResponse) String() string { return proto.CompactTextString(m) }
func (*BanNodeResponse) ProtoMessage()    {}
func (*BanNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{5}
}

func (m *BanNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BanNodeResponse.Unmarshal(m, b)
}
func (m *BanNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BanNodeResponse.Marshal(b, m, deterministic)
}
func (m *BanNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BanNodeResponse.Merge(m, src)
}
func (m *BanNodeResponse) XXX_Size() int {
	return xxx_messageInfo_BanNodeResponse.Size(m)
}
func (m *BanNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BanNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BanNodeResponse proto.InternalMessageInfo

type UnbanNodeRequest struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbanNodeRequest) Reset()         { *m = UnbanNodeRequest{} }
func (m *UnbanNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UnbanNodeRequest) ProtoMessage()    {}
func (*UnbanNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{6}
}

func (m *UnbanNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbanNodeRequest.Unmarshal(m, b)
}
func (m *UnbanNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbanNodeRequest.Marshal(b, m, deterministic)
}
func (m *UnbanNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbanNodeRequest.Merge(m, src)
}
func (m *UnbanNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UnbanNodeRequest.Size(m)
}
func (m *UnbanNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbanNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbanNodeRequest proto.InternalMessageInfo

func (m *UnbanNodeRequest) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type UnbanNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbanNodeResponse) Reset()         { *m = UnbanNodeResponse{} }
func (m *UnbanNodeResponse) String() string { return proto.CompactTextString(m) }
func (*UnbanNodeResponse) ProtoMessage()    {}
func (*UnbanNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{7}
}

func (m *UnbanNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbanNodeResponse.Unmarshal(m, b)
}
func (m *UnbanNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbanNodeResponse.Marshal(b, m, deterministic)
}
func (m *UnbanNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbanNodeResponse.Merge(m, src)
}
func (m *UnbanNodeResponse) XXX_Size() int {
	return xxx_messageInfo_UnbanNodeResponse.Size(m)
}
func (m *UnbanNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbanNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnbanNodeResponse proto.InternalMessageInfo

// DATA MESSAGES
type Profile struct {
	PeerID                 string                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Handle                 string                 `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Location               string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	About                  string                 `protobuf:"bytes,5,opt,name=about,proto3" json:"about,omitempty"`
	ShortDescription       string                 `protobuf:"bytes,6,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Nsfw                   bool                   `protobuf:"varint,7,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Vendor                 bool                   `protobuf:"varint,8,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Moderator              bool                   `protobuf:"varint,9,opt,name=moderator,proto3" json:"moderator,omitempty"`
	ModeratorInfo          *Profile_ModeratorInfo `protobuf:"bytes,10,opt,name=moderatorInfo,proto3" json:"moderatorInfo,omitempty"`
	ContactInfo            *Profile_ContactInfo   `protobuf:"bytes,11,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	Colors                 *Profile_ProfileColors `protobuf:"bytes,12,opt,name=colors,proto3" json:"colors,omitempty"`
	AvatarHashes           *Profile_ImageHashes   `protobuf:"bytes,13,opt,name=avatarHashes,proto3" json:"avatarHashes,omitempty"`
	HeaderHashes           *Profile_ImageHashes   `protobuf:"bytes,14,opt,name=headerHashes,proto3" json:"headerHashes,omitempty"`
	Stats                  *Profile_ProfileStats  `protobuf:"bytes,15,opt,name=stats,proto3" json:"stats,omitempty"`
	PublicKey              string                 `protobuf:"bytes,16,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	StoreAndForwardServers []string               `protobuf:"bytes,17,rep,name=storeAndForwardServers,proto3" json:"storeAndForwardServers,omitempty"`
	LastModified           *timestamp.Timestamp   `protobuf:"bytes,18,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-"`
	XXX_unrecognized       []byte                 `json:"-"`
	XXX_sizecache          int32                  `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Profile) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Profile) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Profile) GetVendor() bool {
	if m != nil {
		return m.Vendor
	}
	return false
}

func (m *Profile) GetModerator() bool {
	if m != nil {
		return m.Moderator
	}
	return false
}

func (m *Profile) GetModeratorInfo() *Profile_ModeratorInfo {
	if m != nil {
		return m.ModeratorInfo
	}
	return nil
}

func (m *Profile) GetContactInfo() *Profile_ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Profile) GetColors() *Profile_ProfileColors {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *Profile) GetAvatarHashes() *Profile_ImageHashes {
	if m != nil {
		return m.AvatarHashes
	}
	return nil
}

func (m *Profile) GetHeaderHashes() *Profile_ImageHashes {
	if m != nil {
		return m.HeaderHashes
	}
	return nil
}

func (m *Profile) GetStats() *Profile_ProfileStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Profile) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Profile) GetStoreAndForwardServers() []string {
	if m != nil {
		return m.StoreAndForwardServers
	}
	return nil
}

func (m *Profile) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type Profile_ProfileColors struct {
	Primary              string   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary            string   `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Highlight            string   `protobuf:"bytes,4,opt,name=highlight,proto3" json:"highlight,omitempty"`
	HighlightText        string   `protobuf:"bytes,5,opt,name=highlightText,proto3" json:"highlightText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ProfileColors) Reset()         { *m = Profile_ProfileColors{} }
func (m *Profile_ProfileColors) String() string { return proto.CompactTextString(m) }
func (*Profile_ProfileColors) ProtoMessage()    {}
func (*Profile_ProfileColors) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 0}
}

func (m *Profile_ProfileColors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ProfileColors.Unmarshal(m, b)
}
func (m *Profile_ProfileColors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ProfileColors.Marshal(b, m, deterministic)
}
func (m *Profile_ProfileColors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ProfileColors.Merge(m, src)
}
func (m *Profile_ProfileColors) XXX_Size() int {
	return xxx_messageInfo_Profile_ProfileColors.Size(m)
}
func (m *Profile_ProfileColors) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ProfileColors.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ProfileColors proto.InternalMessageInfo

func (m *Profile_ProfileColors) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Profile_ProfileColors) GetSecondary() string {
	if m != nil {
		return m.Secondary
	}
	return ""
}

func (m *Profile_ProfileColors) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Profile_ProfileColors) GetHighlight() string {
	if m != nil {
		return m.Highlight
	}
	return ""
}

func (m *Profile_ProfileColors) GetHighlightText() string {
	if m != nil {
		return m.HighlightText
	}
	return ""
}

type Profile_ContactInfo struct {
	Website              string                               `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Email                string                               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                               `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Social               []*Profile_ContactInfo_SocialAccount `protobuf:"bytes,4,rep,name=social,proto3" json:"social,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Profile_ContactInfo) Reset()         { *m = Profile_ContactInfo{} }
func (m *Profile_ContactInfo) String() string { return proto.CompactTextString(m) }
func (*Profile_ContactInfo) ProtoMessage()    {}
func (*Profile_ContactInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 1}
}

func (m *Profile_ContactInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ContactInfo.Unmarshal(m, b)
}
func (m *Profile_ContactInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ContactInfo.Marshal(b, m, deterministic)
}
func (m *Profile_ContactInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ContactInfo.Merge(m, src)
}
func (m *Profile_ContactInfo) XXX_Size() int {
	return xxx_messageInfo_Profile_ContactInfo.Size(m)
}
func (m *Profile_ContactInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ContactInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ContactInfo proto.InternalMessageInfo

func (m *Profile_ContactInfo) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile_ContactInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile_ContactInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile_ContactInfo) GetSocial() []*Profile_ContactInfo_SocialAccount {
	if m != nil {
		return m.Social
	}
	return nil
}

type Profile_ContactInfo_SocialAccount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Proof                string   `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ContactInfo_SocialAccount) Reset()         { *m = Profile_ContactInfo_SocialAccount{} }
func (m *Profile_ContactInfo_SocialAccount) String() string { return proto.CompactTextString(m) }
func (*Profile_ContactInfo_SocialAccount) ProtoMessage()    {}
func (*Profile_ContactInfo_SocialAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 1, 0}
}

func (m *Profile_ContactInfo_SocialAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ContactInfo_SocialAccount.Unmarshal(m, b)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ContactInfo_SocialAccount.Marshal(b, m, deterministic)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ContactInfo_SocialAccount.Merge(m, src)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_Size() int {
	return xxx_messageInfo_Profile_ContactInfo_SocialAccount.Size(m)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ContactInfo_SocialAccount.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ContactInfo_SocialAccount proto.InternalMessageInfo

func (m *Profile_ContactInfo_SocialAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Profile_ContactInfo_SocialAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile_ContactInfo_SocialAccount) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type Profile_ProfileStats struct {
	FollowerCount        uint32   `protobuf:"varint,1,opt,name=followerCount,proto3" json:"followerCount,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,2,opt,name=followingCount,proto3" json:"followingCount,omitempty"`
	ListingCount         uint32   `protobuf:"varint,3,opt,name=listingCount,proto3" json:"listingCount,omitempty"`
	RatingCount          uint32   `protobuf:"varint,4,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	PostCount            uint32   `protobuf:"varint,5,opt,name=postCount,proto3" json:"postCount,omitempty"`
	AverageRating        float32  `protobuf:"fixed32,6,opt,name=averageRating,proto3" json:"averageRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ProfileStats) Reset()         { *m = Profile_ProfileStats{} }
func (m *Profile_ProfileStats) String() string { return proto.CompactTextString(m) }
func (*Profile_ProfileStats) ProtoMessage()    {}
func (*Profile_ProfileStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 2}
}

func (m *Profile_ProfileStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ProfileStats.Unmarshal(m, b)
}
func (m *Profile_ProfileStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ProfileStats.Marshal(b, m, deterministic)
}
func (m *Profile_ProfileStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ProfileStats.Merge(m, src)
}
func (m *Profile_ProfileStats) XXX_Size() int {
	return xxx_messageInfo_Profile_ProfileStats.Size(m)
}
func (m *Profile_ProfileStats) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ProfileStats.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ProfileStats proto.InternalMessageInfo

func (m *Profile_ProfileStats) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetListingCount() uint32 {
	if m != nil {
		return m.ListingCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetRatingCount() uint32 {
	if m != nil {
		return m.RatingCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetAverageRating() float32 {
	if m != nil {
		return m.AverageRating
	}
	return 0
}

// ImageHashes holds image hashes.
type Profile_ImageHashes struct {
	Tiny                 string   `protobuf:"bytes,1,opt,name=tiny,proto3" json:"tiny,omitempty"`
	Small                string   `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	Medium               string   `protobuf:"bytes,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Large                string   `protobuf:"bytes,4,opt,name=large,proto3" json:"large,omitempty"`
	Original             string   `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`
	Filename             string   `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ImageHashes) Reset()         { *m = Profile_ImageHashes{} }
func (m *Profile_ImageHashes) String() string { return proto.CompactTextString(m) }
func (*Profile_ImageHashes) ProtoMessage()    {}
func (*Profile_ImageHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 3}
}

func (m *Profile_ImageHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ImageHashes.Unmarshal(m, b)
}
func (m *Profile_ImageHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ImageHashes.Marshal(b, m, deterministic)
}
func (m *Profile_ImageHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ImageHashes.Merge(m, src)
}
func (m *Profile_ImageHashes) XXX_Size() int {
	return xxx_messageInfo_Profile_ImageHashes.Size(m)
}
func (m *Profile_ImageHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ImageHashes.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ImageHashes proto.InternalMessageInfo

func (m *Profile_ImageHashes) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

func (m *Profile_ImageHashes) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Profile_ImageHashes) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Profile_ImageHashes) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Profile_ImageHashes) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

func (m *Profile_ImageHashes) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type Profile_ModeratorInfo struct {
	Description          string                              `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	TermsAndConditions   string                              `protobuf:"bytes,2,opt,name=termsAndConditions,proto3" json:"termsAndConditions,omitempty"`
	Languages            []string                            `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	AcceptedCurrencies   []string                            `protobuf:"bytes,4,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"`
	Fee                  *Profile_ModeratorInfo_ModeratorFee `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Profile_ModeratorInfo) Reset()         { *m = Profile_ModeratorInfo{} }
func (m *Profile_ModeratorInfo) String() string { return proto.CompactTextString(m) }
func (*Profile_ModeratorInfo) ProtoMessage()    {}
func (*Profile_ModeratorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 4}
}

func (m *Profile_ModeratorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ModeratorInfo.Unmarshal(m, b)
}
func (m *Profile_ModeratorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ModeratorInfo.Marshal(b, m, deterministic)
}
func (m *Profile_ModeratorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ModeratorInfo.Merge(m, src)
}
func (m *Profile_ModeratorInfo) XXX_Size() int {
	return xxx_messageInfo_Profile_ModeratorInfo.Size(m)
}
func (m *Profile_ModeratorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ModeratorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ModeratorInfo proto.InternalMessageInfo

func (m *Profile_ModeratorInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Profile_ModeratorInfo) GetTermsAndConditions() string {
	if m != nil {
		return m.TermsAndConditions
	}
	return ""
}

func (m *Profile_ModeratorInfo) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *Profile_ModeratorInfo) GetAcceptedCurrencies() []string {
	if m != nil {
		return m.AcceptedCurrencies
	}
	return nil
}

func (m *Profile_ModeratorInfo) GetFee() *Profile_ModeratorInfo_ModeratorFee {
	if m != nil {
		return m.Fee
	}
	return nil
}

type Profile_ModeratorInfo_ModeratorFee struct {
	FixedFee             *CurrencyValue                             `protobuf:"bytes,1,opt,name=fixedFee,proto3" json:"fixedFee,omitempty"`
	Percentage           float32                                    `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	FeeType              Profile_ModeratorInfo_ModeratorFee_FeeType `protobuf:"varint,3,opt,name=feeType,proto3,enum=pb.Profile_ModeratorInfo_ModeratorFee_FeeType" json:"feeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Profile_ModeratorInfo_ModeratorFee) Reset()         { *m = Profile_ModeratorInfo_ModeratorFee{} }
func (m *Profile_ModeratorInfo_ModeratorFee) String() string { return proto.CompactTextString(m) }
func (*Profile_ModeratorInfo_ModeratorFee) ProtoMessage()    {}
func (*Profile_ModeratorInfo_ModeratorFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 4, 0}
}

func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Unmarshal(m, b)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Marshal(b, m, deterministic)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Merge(m, src)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Size() int {
	return xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Size(m)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee proto.InternalMessageInfo

func (m *Profile_ModeratorInfo_ModeratorFee) GetFixedFee() *CurrencyValue {
	if m != nil {
		return m.FixedFee
	}
	return nil
}

func (m *Profile_ModeratorInfo_ModeratorFee) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Profile_ModeratorInfo_ModeratorFee) GetFeeType() Profile_ModeratorInfo_ModeratorFee_FeeType {
	if m != nil {
		return m.FeeType
	}
	return Profile_ModeratorInfo_ModeratorFee_FixedFee
}

type Listing struct {
	Slug                 string                    `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	VendorID             *ID                       `protobuf:"bytes,2,opt,name=vendorID,proto3" json:"vendorID,omitempty"`
	Metadata             *Listing_Metadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Item                 *Listing_Item             `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	ShippingOptions      []*Listing_ShippingOption `protobuf:"bytes,5,rep,name=shippingOptions,proto3" json:"shippingOptions,omitempty"`
	Taxes                []*Listing_Tax            `protobuf:"bytes,6,rep,name=taxes,proto3" json:"taxes,omitempty"`
	Coupons              []*Listing_Coupon         `protobuf:"bytes,7,rep,name=coupons,proto3" json:"coupons,omitempty"`
	Moderators           []string                  `protobuf:"bytes,8,rep,name=moderators,proto3" json:"moderators,omitempty"`
	TermsAndConditions   string                    `protobuf:"bytes,9,opt,name=termsAndConditions,proto3" json:"termsAndConditions,omitempty"`
	RefundPolicy         string                    `protobuf:"bytes,10,opt,name=refundPolicy,proto3" json:"refundPolicy,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Listing) Reset()         { *m = Listing{} }
func (m *Listing) String() string { return proto.CompactTextString(m) }
func (*Listing) ProtoMessage()    {}
func (*Listing) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9}
}

func (m *Listing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing.Unmarshal(m, b)
}
func (m *Listing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing.Marshal(b, m, deterministic)
}
func (m *Listing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing.Merge(m, src)
}
func (m *Listing) XXX_Size() int {
	return xxx_messageInfo_Listing.Size(m)
}
func (m *Listing) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing.DiscardUnknown(m)
}

var xxx_messageInfo_Listing proto.InternalMessageInfo

func (m *Listing) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Listing) GetVendorID() *ID {
	if m != nil {
		return m.VendorID
	}
	return nil
}

func (m *Listing) GetMetadata() *Listing_Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Listing) GetItem() *Listing_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *Listing) GetShippingOptions() []*Listing_ShippingOption {
	if m != nil {
		return m.ShippingOptions
	}
	return nil
}

func (m *Listing) GetTaxes() []*Listing_Tax {
	if m != nil {
		return m.Taxes
	}
	return nil
}

func (m *Listing) GetCoupons() []*Listing_Coupon {
	if m != nil {
		return m.Coupons
	}
	return nil
}

func (m *Listing) GetModerators() []string {
	if m != nil {
		return m.Moderators
	}
	return nil
}

func (m *Listing) GetTermsAndConditions() string {
	if m != nil {
		return m.TermsAndConditions
	}
	return ""
}

func (m *Listing) GetRefundPolicy() string {
	if m != nil {
		return m.RefundPolicy
	}
	return ""
}

type Listing_Metadata struct {
	Version              uint32                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ContractType         Listing_Metadata_ContractType `protobuf:"varint,2,opt,name=contractType,proto3,enum=pb.Listing_Metadata_ContractType" json:"contractType,omitempty"`
	Format               Listing_Metadata_Format       `protobuf:"varint,3,opt,name=format,proto3,enum=pb.Listing_Metadata_Format" json:"format,omitempty"`
	Expiry               *timestamp.Timestamp          `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	AcceptedCurrencies   []string                      `protobuf:"bytes,5,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"`
	Language             string                        `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	EscrowTimeoutHours   uint32                        `protobuf:"varint,7,opt,name=escrowTimeoutHours,proto3" json:"escrowTimeoutHours,omitempty"`
	PricingCurrency      *Currency                     `protobuf:"bytes,9,opt,name=pricingCurrency,proto3" json:"pricingCurrency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Listing_Metadata) Reset()         { *m = Listing_Metadata{} }
func (m *Listing_Metadata) String() string { return proto.CompactTextString(m) }
func (*Listing_Metadata) ProtoMessage()    {}
func (*Listing_Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 0}
}

func (m *Listing_Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Metadata.Unmarshal(m, b)
}
func (m *Listing_Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Metadata.Marshal(b, m, deterministic)
}
func (m *Listing_Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Metadata.Merge(m, src)
}
func (m *Listing_Metadata) XXX_Size() int {
	return xxx_messageInfo_Listing_Metadata.Size(m)
}
func (m *Listing_Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Metadata proto.InternalMessageInfo

func (m *Listing_Metadata) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Listing_Metadata) GetContractType() Listing_Metadata_ContractType {
	if m != nil {
		return m.ContractType
	}
	return Listing_Metadata_PHYSICAL_GOOD
}

func (m *Listing_Metadata) GetFormat() Listing_Metadata_Format {
	if m != nil {
		return m.Format
	}
	return Listing_Metadata_FIXED_PRICE
}

func (m *Listing_Metadata) GetExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func (m *Listing_Metadata) GetAcceptedCurrencies() []string {
	if m != nil {
		return m.AcceptedCurrencies
	}
	return nil
}

func (m *Listing_Metadata) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Listing_Metadata) GetEscrowTimeoutHours() uint32 {
	if m != nil {
		return m.EscrowTimeoutHours
	}
	return 0
}

func (m *Listing_Metadata) GetPricingCurrency() *Currency {
	if m != nil {
		return m.PricingCurrency
	}
	return nil
}

type Listing_Item struct {
	Title                      string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description                string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ProcessingTime             string                 `protobuf:"bytes,3,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	Nsfw                       bool                   `protobuf:"varint,4,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Tags                       []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Images                     []*Listing_Item_Image  `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Categories                 []string               `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	Grams                      float32                `protobuf:"fixed32,8,opt,name=grams,proto3" json:"grams,omitempty"`
	Condition                  string                 `protobuf:"bytes,9,opt,name=condition,proto3" json:"condition,omitempty"`
	Options                    []*Listing_Item_Option `protobuf:"bytes,10,rep,name=options,proto3" json:"options,omitempty"`
	Skus                       []*Listing_Item_Sku    `protobuf:"bytes,11,rep,name=skus,proto3" json:"skus,omitempty"`
	Price                      string                 `protobuf:"bytes,12,opt,name=price,proto3" json:"price,omitempty"`
	CryptoListingCurrencyCode  string                 `protobuf:"bytes,13,opt,name=cryptoListingCurrencyCode,proto3" json:"cryptoListingCurrencyCode,omitempty"`
	CryptoListingPriceModifier float32                `protobuf:"fixed32,14,opt,name=cryptoListingPriceModifier,proto3" json:"cryptoListingPriceModifier,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}               `json:"-"`
	XXX_unrecognized           []byte                 `json:"-"`
	XXX_sizecache              int32                  `json:"-"`
}

func (m *Listing_Item) Reset()         { *m = Listing_Item{} }
func (m *Listing_Item) String() string { return proto.CompactTextString(m) }
func (*Listing_Item) ProtoMessage()    {}
func (*Listing_Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 1}
}

func (m *Listing_Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item.Unmarshal(m, b)
}
func (m *Listing_Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item.Marshal(b, m, deterministic)
}
func (m *Listing_Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item.Merge(m, src)
}
func (m *Listing_Item) XXX_Size() int {
	return xxx_messageInfo_Listing_Item.Size(m)
}
func (m *Listing_Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item proto.InternalMessageInfo

func (m *Listing_Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Listing_Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing_Item) GetProcessingTime() string {
	if m != nil {
		return m.ProcessingTime
	}
	return ""
}

func (m *Listing_Item) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Listing_Item) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Listing_Item) GetImages() []*Listing_Item_Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *Listing_Item) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *Listing_Item) GetGrams() float32 {
	if m != nil {
		return m.Grams
	}
	return 0
}

func (m *Listing_Item) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

func (m *Listing_Item) GetOptions() []*Listing_Item_Option {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Listing_Item) GetSkus() []*Listing_Item_Sku {
	if m != nil {
		return m.Skus
	}
	return nil
}

func (m *Listing_Item) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Listing_Item) GetCryptoListingCurrencyCode() string {
	if m != nil {
		return m.CryptoListingCurrencyCode
	}
	return ""
}

func (m *Listing_Item) GetCryptoListingPriceModifier() float32 {
	if m != nil {
		return m.CryptoListingPriceModifier
	}
	return 0
}

type Listing_Item_Option struct {
	Name                 string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Variants             []*Listing_Item_Option_Variant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Listing_Item_Option) Reset()         { *m = Listing_Item_Option{} }
func (m *Listing_Item_Option) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Option) ProtoMessage()    {}
func (*Listing_Item_Option) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 1, 0}
}

func (m *Listing_Item_Option) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Option.Unmarshal(m, b)
}
func (m *Listing_Item_Option) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Option.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Option) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Option.Merge(m, src)
}
func (m *Listing_Item_Option) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Option.Size(m)
}
func (m *Listing_Item_Option) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Option.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Option proto.InternalMessageInfo

func (m *Listing_Item_Option) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_Item_Option) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Listing_Item_Option) GetVariants() []*Listing_Item_Option_Variant {
	if m != nil {
		return m.Variants
	}
	return nil
}

type Listing_Item_Option_Variant struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image                *Listing_Item_Image `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Listing_Item_Option_Variant) Reset()         { *m = Listing_Item_Option_Variant{} }
func (m *Listing_Item_Option_Variant) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Option_Variant) ProtoMessage()    {}
func (*Listing_Item_Option_Variant) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 1, 0, 0}
}

func (m *Listing_Item_Option_Variant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Option_Variant.Unmarshal(m, b)
}
func (m *Listing_Item_Option_Variant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Option_Variant.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Option_Variant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Option_Variant.Merge(m, src)
}
func (m *Listing_Item_Option_Variant) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Option_Variant.Size(m)
}
func (m *Listing_Item_Option_Variant) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Option_Variant.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Option_Variant proto.InternalMessageInfo

func (m *Listing_Item_Option_Variant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_Item_Option_Variant) GetImage() *Listing_Item_Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type Listing_Item_Sku struct {
	Selections           []*Listing_Item_Sku_Selection `protobuf:"bytes,1,rep,name=selections,proto3" json:"selections,omitempty"`
	ProductID            string                        `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity             string                        `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Surcharge            string                        `protobuf:"bytes,4,opt,name=surcharge,proto3" json:"surcharge,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *Listing_Item_Sku) Reset()         { *m = Listing_Item_Sku{} }
func (m *Listing_Item_Sku) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Sku) ProtoMessage()    {}
func (*Listing_Item_Sku) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 1, 1}
}

func (m *Listing_Item_Sku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Sku.Unmarshal(m, b)
}
func (m *Listing_Item_Sku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Sku.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Sku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Sku.Merge(m, src)
}
func (m *Listing_Item_Sku) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Sku.Size(m)
}
func (m *Listing_Item_Sku) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Sku.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Sku proto.InternalMessageInfo

func (m *Listing_Item_Sku) GetSelections() []*Listing_Item_Sku_Selection {
	if m != nil {
		return m.Selections
	}
	return nil
}

func (m *Listing_Item_Sku) GetProductID() string {
	if m != nil {
		return m.ProductID
	}
	return ""
}

func (m *Listing_Item_Sku) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *Listing_Item_Sku) GetSurcharge() string {
	if m != nil {
		return m.Surcharge
	}
	return ""
}

type Listing_Item_Sku_Selection struct {
	Option               string   `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Variant              string   `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing_Item_Sku_Selection) Reset()         { *m = Listing_Item_Sku_Selection{} }
func (m *Listing_Item_Sku_Selection) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Sku_Selection) ProtoMessage()    {}
func (*Listing_Item_Sku_Selection) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 1, 1, 0}
}

func (m *Listing_Item_Sku_Selection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Sku_Selection.Unmarshal(m, b)
}
func (m *Listing_Item_Sku_Selection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Sku_Selection.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Sku_Selection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Sku_Selection.Merge(m, src)
}
func (m *Listing_Item_Sku_Selection) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Sku_Selection.Size(m)
}
func (m *Listing_Item_Sku_Selection) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Sku_Selection.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Sku_Selection proto.InternalMessageInfo

func (m *Listing_Item_Sku_Selection) GetOption() string {
	if m != nil {
		return m.Option
	}
	return ""
}

func (m *Listing_Item_Sku_Selection) GetVariant() string {
	if m != nil {
		return m.Variant
	}
	return ""
}

type Listing_Item_Image struct {
	Filename             string   `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Original             string   `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	Large                string   `protobuf:"bytes,3,opt,name=large,proto3" json:"large,omitempty"`
	Medium               string   `protobuf:"bytes,4,opt,name=medium,proto3" json:"medium,omitempty"`
	Small                string   `protobuf:"bytes,5,opt,name=small,proto3" json:"small,omitempty"`
	Tiny                 string   `protobuf:"bytes,6,opt,name=tiny,proto3" json:"tiny,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing_Item_Image) Reset()         { *m = Listing_Item_Image{} }
func (m *Listing_Item_Image) String() string { return proto.CompactTextString(m) }
func (*Listing_Item_Image) ProtoMessage()    {}
func (*Listing_Item_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 1, 2}
}

func (m *Listing_Item_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Item_Image.Unmarshal(m, b)
}
func (m *Listing_Item_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Item_Image.Marshal(b, m, deterministic)
}
func (m *Listing_Item_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Item_Image.Merge(m, src)
}
func (m *Listing_Item_Image) XXX_Size() int {
	return xxx_messageInfo_Listing_Item_Image.Size(m)
}
func (m *Listing_Item_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Item_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Item_Image proto.InternalMessageInfo

func (m *Listing_Item_Image) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *Listing_Item_Image) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

func (m *Listing_Item_Image) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Listing_Item_Image) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Listing_Item_Image) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Listing_Item_Image) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

type Listing_ShippingOption struct {
	Name                 string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 Listing_ShippingOption_ShippingType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.Listing_ShippingOption_ShippingType" json:"type,omitempty"`
	Regions              []CountryCode                       `protobuf:"varint,3,rep,packed,name=regions,proto3,enum=CountryCode" json:"regions,omitempty"`
	Services             []*Listing_ShippingOption_Service   `protobuf:"bytes,4,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Listing_ShippingOption) Reset()         { *m = Listing_ShippingOption{} }
func (m *Listing_ShippingOption) String() string { return proto.CompactTextString(m) }
func (*Listing_ShippingOption) ProtoMessage()    {}
func (*Listing_ShippingOption) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 2}
}

func (m *Listing_ShippingOption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_ShippingOption.Unmarshal(m, b)
}
func (m *Listing_ShippingOption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_ShippingOption.Marshal(b, m, deterministic)
}
func (m *Listing_ShippingOption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_ShippingOption.Merge(m, src)
}
func (m *Listing_ShippingOption) XXX_Size() int {
	return xxx_messageInfo_Listing_ShippingOption.Size(m)
}
func (m *Listing_ShippingOption) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_ShippingOption.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_ShippingOption proto.InternalMessageInfo

func (m *Listing_ShippingOption) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_ShippingOption) GetType() Listing_ShippingOption_ShippingType {
	if m != nil {
		return m.Type
	}
	return Listing_ShippingOption_LOCAL_PICKUP
}

func (m *Listing_ShippingOption) GetRegions() []CountryCode {
	if m != nil {
		return m.Regions
	}
	return nil
}

func (m *Listing_ShippingOption) GetServices() []*Listing_ShippingOption_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Listing_ShippingOption_Service struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	EstimatedDelivery    string   `protobuf:"bytes,2,opt,name=estimatedDelivery,proto3" json:"estimatedDelivery,omitempty"`
	Price                string   `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	AdditionalItemPrice  string   `protobuf:"bytes,4,opt,name=additionalItemPrice,proto3" json:"additionalItemPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listing_ShippingOption_Service) Reset()         { *m = Listing_ShippingOption_Service{} }
func (m *Listing_ShippingOption_Service) String() string { return proto.CompactTextString(m) }
func (*Listing_ShippingOption_Service) ProtoMessage()    {}
func (*Listing_ShippingOption_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 2, 0}
}

func (m *Listing_ShippingOption_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_ShippingOption_Service.Unmarshal(m, b)
}
func (m *Listing_ShippingOption_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_ShippingOption_Service.Marshal(b, m, deterministic)
}
func (m *Listing_ShippingOption_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_ShippingOption_Service.Merge(m, src)
}
func (m *Listing_ShippingOption_Service) XXX_Size() int {
	return xxx_messageInfo_Listing_ShippingOption_Service.Size(m)
}
func (m *Listing_ShippingOption_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_ShippingOption_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_ShippingOption_Service proto.InternalMessageInfo

func (m *Listing_ShippingOption_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listing_ShippingOption_Service) GetEstimatedDelivery() string {
	if m != nil {
		return m.EstimatedDelivery
	}
	return ""
}

func (m *Listing_ShippingOption_Service) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Listing_ShippingOption_Service) GetAdditionalItemPrice() string {
	if m != nil {
		return m.AdditionalItemPrice
	}
	return ""
}

type Listing_Tax struct {
	TaxType              string        `protobuf:"bytes,1,opt,name=taxType,proto3" json:"taxType,omitempty"`
	TaxRegions           []CountryCode `protobuf:"varint,2,rep,packed,name=taxRegions,proto3,enum=CountryCode" json:"taxRegions,omitempty"`
	TaxShipping          bool          `protobuf:"varint,3,opt,name=taxShipping,proto3" json:"taxShipping,omitempty"`
	Percentage           float32       `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Listing_Tax) Reset()         { *m = Listing_Tax{} }
func (m *Listing_Tax) String() string { return proto.CompactTextString(m) }
func (*Listing_Tax) ProtoMessage()    {}
func (*Listing_Tax) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 3}
}

func (m *Listing_Tax) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Tax.Unmarshal(m, b)
}
func (m *Listing_Tax) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Tax.Marshal(b, m, deterministic)
}
func (m *Listing_Tax) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Tax.Merge(m, src)
}
func (m *Listing_Tax) XXX_Size() int {
	return xxx_messageInfo_Listing_Tax.Size(m)
}
func (m *Listing_Tax) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Tax.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Tax proto.InternalMessageInfo

func (m *Listing_Tax) GetTaxType() string {
	if m != nil {
		return m.TaxType
	}
	return ""
}

func (m *Listing_Tax) GetTaxRegions() []CountryCode {
	if m != nil {
		return m.TaxRegions
	}
	return nil
}

func (m *Listing_Tax) GetTaxShipping() bool {
	if m != nil {
		return m.TaxShipping
	}
	return false
}

func (m *Listing_Tax) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

type Listing_Coupon struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Types that are valid to be assigned to Code:
	//	*Listing_Coupon_Hash
	//	*Listing_Coupon_DiscountCode
	Code isListing_Coupon_Code `protobuf_oneof:"code"`
	// Types that are valid to be assigned to Discount:
	//	*Listing_Coupon_PercentDiscount
	//	*Listing_Coupon_PriceDiscount
	Discount             isListing_Coupon_Discount `protobuf_oneof:"discount"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Listing_Coupon) Reset()         { *m = Listing_Coupon{} }
func (m *Listing_Coupon) String() string { return proto.CompactTextString(m) }
func (*Listing_Coupon) ProtoMessage()    {}
func (*Listing_Coupon) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{9, 4}
}

func (m *Listing_Coupon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listing_Coupon.Unmarshal(m, b)
}
func (m *Listing_Coupon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listing_Coupon.Marshal(b, m, deterministic)
}
func (m *Listing_Coupon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listing_Coupon.Merge(m, src)
}
func (m *Listing_Coupon) XXX_Size() int {
	return xxx_messageInfo_Listing_Coupon.Size(m)
}
func (m *Listing_Coupon) XXX_DiscardUnknown() {
	xxx_messageInfo_Listing_Coupon.DiscardUnknown(m)
}

var xxx_messageInfo_Listing_Coupon proto.InternalMessageInfo

func (m *Listing_Coupon) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type isListing_Coupon_Code interface {
	isListing_Coupon_Code()
}

type Listing_Coupon_Hash struct {
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3,oneof"`
}

type Listing_Coupon_DiscountCode struct {
	DiscountCode string `protobuf:"bytes,3,opt,name=discountCode,proto3,oneof"`
}

func (*Listing_Coupon_Hash) isListing_Coupon_Code() {}

func (*Listing_Coupon_DiscountCode) isListing_Coupon_Code() {}

func (m *Listing_Coupon) GetCode() isListing_Coupon_Code {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *Listing_Coupon) GetHash() string {
	if x, ok := m.GetCode().(*Listing_Coupon_Hash); ok {
		return x.Hash
	}
	return ""
}

func (m *Listing_Coupon) GetDiscountCode() string {
	if x, ok := m.GetCode().(*Listing_Coupon_DiscountCode); ok {
		return x.DiscountCode
	}
	return ""
}

type isListing_Coupon_Discount interface {
	isListing_Coupon_Discount()
}

type Listing_Coupon_PercentDiscount struct {
	PercentDiscount float32 `protobuf:"fixed32,4,opt,name=percentDiscount,proto3,oneof"`
}

type Listing_Coupon_PriceDiscount struct {
	PriceDiscount string `protobuf:"bytes,5,opt,name=priceDiscount,proto3,oneof"`
}

func (*Listing_Coupon_PercentDiscount) isListing_Coupon_Discount() {}

func (*Listing_Coupon_PriceDiscount) isListing_Coupon_Discount() {}

func (m *Listing_Coupon) GetDiscount() isListing_Coupon_Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func (m *Listing_Coupon) GetPercentDiscount() float32 {
	if x, ok := m.GetDiscount().(*Listing_Coupon_PercentDiscount); ok {
		return x.PercentDiscount
	}
	return 0
}

func (m *Listing_Coupon) GetPriceDiscount() string {
	if x, ok := m.GetDiscount().(*Listing_Coupon_PriceDiscount); ok {
		return x.PriceDiscount
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Listing_Coupon) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Listing_Coupon_Hash)(nil),
		(*Listing_Coupon_DiscountCode)(nil),
		(*Listing_Coupon_PercentDiscount)(nil),
		(*Listing_Coupon_PriceDiscount)(nil),
	}
}

type SignedListing struct {
	Listing              *Listing `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignedListing) Reset()         { *m = SignedListing{} }
func (m *SignedListing) String() string { return proto.CompactTextString(m) }
func (*SignedListing) ProtoMessage()    {}
func (*SignedListing) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{10}
}

func (m *SignedListing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedListing.Unmarshal(m, b)
}
func (m *SignedListing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedListing.Marshal(b, m, deterministic)
}
func (m *SignedListing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedListing.Merge(m, src)
}
func (m *SignedListing) XXX_Size() int {
	return xxx_messageInfo_SignedListing.Size(m)
}
func (m *SignedListing) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedListing.DiscardUnknown(m)
}

var xxx_messageInfo_SignedListing proto.InternalMessageInfo

func (m *SignedListing) GetListing() *Listing {
	if m != nil {
		return m.Listing
	}
	return nil
}

func (m *SignedListing) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *SignedListing) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Profile_ModeratorInfo_ModeratorFee_FeeType", Profile_ModeratorInfo_ModeratorFee_FeeType_name, Profile_ModeratorInfo_ModeratorFee_FeeType_value)
	proto.RegisterEnum("pb.Listing_Metadata_ContractType", Listing_Metadata_ContractType_name, Listing_Metadata_ContractType_value)
	proto.RegisterEnum("pb.Listing_Metadata_Format", Listing_Metadata_Format_name, Listing_Metadata_Format_value)
	proto.RegisterEnum("pb.Listing_ShippingOption_ShippingType", Listing_ShippingOption_ShippingType_name, Listing_ShippingOption_ShippingType_value)
	proto.RegisterType((*SubscribeRequest)(nil), "pb.SubscribeRequest")
	proto.RegisterType((*UserData)(nil), "pb.UserData")
	proto.RegisterType((*CrawlNodeRequest)(nil), "pb.CrawlNodeRequest")
	proto.RegisterType((*CrawlNodeResponse)(nil), "pb.CrawlNodeResponse")
	proto.RegisterType((*BanNodeRequest)(nil), "pb.BanNodeRequest")
	proto.RegisterType((*BanNodeResponse)(nil), "pb.BanNodeResponse")
	proto.RegisterType((*UnbanNodeRequest)(nil), "pb.UnbanNodeRequest")
	proto.RegisterType((*UnbanNodeResponse)(nil), "pb.UnbanNodeResponse")
	proto.RegisterType((*Profile)(nil), "pb.Profile")
	proto.RegisterType((*Profile_ProfileColors)(nil), "pb.Profile.ProfileColors")
	proto.RegisterType((*Profile_ContactInfo)(nil), "pb.Profile.ContactInfo")
	proto.RegisterType((*Profile_ContactInfo_SocialAccount)(nil), "pb.Profile.ContactInfo.SocialAccount")
	proto.RegisterType((*Profile_ProfileStats)(nil), "pb.Profile.ProfileStats")
	proto.RegisterType((*Profile_ImageHashes)(nil), "pb.Profile.ImageHashes")
	proto.RegisterType((*Profile_ModeratorInfo)(nil), "pb.Profile.ModeratorInfo")
	proto.RegisterType((*Profile_ModeratorInfo_ModeratorFee)(nil), "pb.Profile.ModeratorInfo.ModeratorFee")
	proto.RegisterType((*Listing)(nil), "pb.Listing")
	proto.RegisterType((*Listing_Metadata)(nil), "pb.Listing.Metadata")
	proto.RegisterType((*Listing_Item)(nil), "pb.Listing.Item")
	proto.RegisterType((*Listing_Item_Option)(nil), "pb.Listing.Item.Option")
	proto.RegisterType((*Listing_Item_Option_Variant)(nil), "pb.Listing.Item.Option.Variant")
	proto.RegisterType((*Listing_Item_Sku)(nil), "pb.Listing.Item.Sku")
	proto.RegisterType((*Listing_Item_Sku_Selection)(nil), "pb.Listing.Item.Sku.Selection")
	proto.RegisterType((*Listing_Item_Image)(nil), "pb.Listing.Item.Image")
	proto.RegisterType((*Listing_ShippingOption)(nil), "pb.Listing.ShippingOption")
	proto.RegisterType((*Listing_ShippingOption_Service)(nil), "pb.Listing.ShippingOption.Service")
	proto.RegisterType((*Listing_Tax)(nil), "pb.Listing.Tax")
	proto.RegisterType((*Listing_Coupon)(nil), "pb.Listing.Coupon")
	proto.RegisterType((*SignedListing)(nil), "pb.SignedListing")
}

func init() { proto.RegisterFile("crawler.proto", fileDescriptor_84c7eabcfe7807d1) }

var fileDescriptor_84c7eabcfe7807d1 = []byte{
	// 2250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x58, 0x4d, 0x73, 0xdb, 0xc8,
	0xd1, 0x16, 0x48, 0x8a, 0x1f, 0x4d, 0x52, 0xa2, 0xc6, 0x5e, 0x2f, 0x17, 0xef, 0x5b, 0x6b, 0x87,
	0x65, 0x6b, 0x5d, 0x8e, 0xc3, 0xb5, 0xe5, 0x54, 0x2a, 0xb1, 0xb3, 0x4e, 0xc9, 0xa4, 0xb4, 0x62,
	0xf9, 0x43, 0xaa, 0xa1, 0xec, 0x8a, 0x4f, 0x5b, 0x43, 0x60, 0x08, 0xa2, 0x0c, 0x62, 0xb8, 0x33,
	0x03, 0x7d, 0xfc, 0x8a, 0x54, 0x25, 0x87, 0xe4, 0x92, 0xca, 0x2d, 0x3f, 0x24, 0x97, 0xe4, 0x27,
	0xe4, 0x90, 0x53, 0x0e, 0x39, 0xa5, 0x72, 0x4b, 0xce, 0xa9, 0xf9, 0x00, 0x08, 0x50, 0xa2, 0x9d,
	0x13, 0xd1, 0x4f, 0x3f, 0x8d, 0x19, 0xf4, 0xf4, 0xf4, 0x3c, 0x1c, 0x68, 0x7b, 0x9c, 0x9c, 0x47,
	0x94, 0xf7, 0x17, 0x9c, 0x49, 0x86, 0x4a, 0x8b, 0x89, 0x7b, 0x3b, 0x60, 0x2c, 0x88, 0xe8, 0xd7,
	0x1a, 0x99, 0x24, 0xd3, 0xaf, 0x65, 0x38, 0xa7, 0x42, 0x92, 0xf9, 0xc2, 0x90, 0x5c, 0xe4, 0xb1,
	0x24, 0x96, 0xfc, 0xd2, 0x63, 0x3e, 0x15, 0x16, 0x6b, 0x79, 0x6c, 0x3e, 0x67, 0xb1, 0xb1, 0x7a,
	0x08, 0x3a, 0xe3, 0x64, 0x22, 0x3c, 0x1e, 0x4e, 0x28, 0xa6, 0xdf, 0x27, 0x54, 0xc8, 0xde, 0x1f,
	0x1d, 0xa8, 0xbf, 0x15, 0x94, 0x0f, 0x89, 0x24, 0xe8, 0x2b, 0xa8, 0x2d, 0x38, 0x9b, 0x86, 0x11,
	0xed, 0x3a, 0x77, 0x9c, 0xfb, 0xcd, 0xbd, 0x66, 0x7f, 0x31, 0xe9, 0x9f, 0x18, 0xe8, 0x68, 0x03,
	0xa7, 0x5e, 0xf4, 0x23, 0xa8, 0x45, 0xa1, 0x90, 0x61, 0x1c, 0x74, 0x4b, 0x9a, 0xb8, 0xa3, 0x88,
	0xe3, 0x30, 0x88, 0xa9, 0xff, 0xca, 0x38, 0x14, 0xdd, 0x72, 0xd0, 0x53, 0x00, 0x7a, 0xb1, 0x08,
	0x39, 0x91, 0x21, 0x8b, 0xbb, 0x65, 0x1d, 0xe1, 0xf6, 0xcd, 0x07, 0xf5, 0xd3, 0x0f, 0xea, 0x9f,
	0xa6, 0x1f, 0x84, 0x73, 0xec, 0x17, 0x55, 0xa8, 0xf8, 0x44, 0x92, 0xde, 0x2e, 0x74, 0x06, 0x2a,
	0x29, 0x6f, 0x98, 0x9f, 0x4e, 0x1e, 0x21, 0xa8, 0x2c, 0x28, 0xe5, 0x7a, 0xb2, 0x0d, 0xac, 0x9f,
	0x7b, 0x37, 0x60, 0x27, 0xc7, 0x13, 0x0b, 0x16, 0x0b, 0xda, 0xbb, 0x0b, 0x5b, 0x2f, 0x48, 0xfc,
	0xa9, 0xd0, 0x1d, 0xd8, 0xce, 0x58, 0x36, 0x70, 0x17, 0x3a, 0x6f, 0xe3, 0xc9, 0xa7, 0x43, 0x6f,
	0xc0, 0x4e, 0x8e, 0x67, 0x83, 0xff, 0xbe, 0x0d, 0x35, 0x9b, 0x3c, 0x74, 0x0b, 0xaa, 0x8a, 0x38,
	0x1a, 0xda, 0x30, 0x6b, 0xa9, 0x97, 0xc5, 0x64, 0x4e, 0x75, 0x1a, 0x1b, 0x58, 0x3f, 0x2b, 0xee,
	0x8c, 0xc4, 0x7e, 0x44, 0x75, 0xaa, 0x1a, 0xd8, 0x5a, 0xc8, 0x85, 0x7a, 0xc4, 0x3c, 0x93, 0xc4,
	0x8a, 0xf6, 0x64, 0x36, 0xba, 0x09, 0x9b, 0x64, 0xc2, 0x12, 0xd9, 0xdd, 0xd4, 0x0e, 0x63, 0xa0,
	0x07, 0xd0, 0x11, 0x33, 0xc6, 0xe5, 0x90, 0xaa, 0x55, 0x5f, 0xe8, 0xc8, 0xaa, 0x26, 0x5c, 0xc1,
	0xf5, 0x4c, 0xc4, 0xf4, 0xbc, 0x5b, 0xbb, 0xe3, 0xdc, 0xaf, 0x63, 0xfd, 0xac, 0x66, 0x72, 0x46,
	0x63, 0x9f, 0xf1, 0x6e, 0x5d, 0xa3, 0xd6, 0x42, 0xff, 0x0f, 0x8d, 0x39, 0xf3, 0x29, 0x27, 0x92,
	0xf1, 0x6e, 0x43, 0xbb, 0x96, 0x00, 0xfa, 0x05, 0xb4, 0x33, 0x63, 0x14, 0x4f, 0x59, 0x17, 0xf4,
	0x8a, 0x7f, 0x91, 0x2b, 0xa6, 0xfe, 0xeb, 0x3c, 0x01, 0x17, 0xf9, 0xe8, 0x67, 0xd0, 0xf4, 0x58,
	0x2c, 0x89, 0x27, 0x75, 0x78, 0x53, 0x87, 0x7f, 0x9e, 0x0f, 0x1f, 0x2c, 0xdd, 0x38, 0xcf, 0x45,
	0x8f, 0xa1, 0xea, 0xb1, 0x88, 0x71, 0xd1, 0x6d, 0x5d, 0x1d, 0xd4, 0xfe, 0x0e, 0x34, 0x01, 0x5b,
	0x22, 0x7a, 0x06, 0x2d, 0x72, 0x46, 0x24, 0xe1, 0x47, 0x44, 0xcc, 0xa8, 0xe8, 0xb6, 0xaf, 0x0e,
	0x37, 0x9a, 0x93, 0x80, 0x1a, 0x37, 0x2e, 0x90, 0x55, 0xf0, 0x8c, 0x12, 0x9f, 0xa6, 0xc1, 0x5b,
	0x9f, 0x08, 0xce, 0x93, 0x51, 0x1f, 0x36, 0x85, 0x24, 0x52, 0x74, 0xb7, 0x75, 0x54, 0xf7, 0x9a,
	0xb9, 0x8e, 0x95, 0x1f, 0x1b, 0x9a, 0x4a, 0xfb, 0x22, 0x99, 0x44, 0xa1, 0xf7, 0x92, 0x5e, 0x76,
	0x3b, 0x7a, 0x1d, 0x97, 0x00, 0xfa, 0x09, 0xdc, 0x12, 0x92, 0x71, 0xba, 0x1f, 0xfb, 0x87, 0x8c,
	0x9f, 0x13, 0xee, 0x8f, 0x29, 0x3f, 0xa3, 0x5c, 0x74, 0x77, 0xee, 0x94, 0xef, 0x37, 0xf0, 0x1a,
	0x2f, 0x7a, 0x0e, 0xad, 0x88, 0x08, 0xf9, 0x9a, 0xf9, 0xe1, 0x34, 0xa4, 0x7e, 0x17, 0x7d, 0x72,
	0x7f, 0x16, 0xf8, 0xee, 0x1f, 0x1c, 0x68, 0x17, 0x32, 0x8b, 0xba, 0xaa, 0x8f, 0x84, 0x73, 0xc2,
	0x2f, 0x6d, 0xb5, 0xa7, 0xa6, 0xfa, 0x02, 0x41, 0x3d, 0x16, 0xfb, 0xca, 0x67, 0x6a, 0x7e, 0x09,
	0xa8, 0x12, 0x94, 0xf4, 0x42, 0xda, 0xb2, 0xd7, 0xcf, 0x2a, 0x62, 0x16, 0x06, 0xb3, 0x28, 0x0c,
	0x66, 0xd2, 0x56, 0xfd, 0x12, 0x40, 0x77, 0xa1, 0x9d, 0x19, 0xa7, 0x2a, 0xd4, 0x94, 0x7f, 0x11,
	0x74, 0xff, 0xed, 0x40, 0x33, 0x57, 0x31, 0x6a, 0x7e, 0xe7, 0x74, 0x22, 0x42, 0x49, 0xd3, 0xf9,
	0x59, 0x53, 0x6d, 0x23, 0x3a, 0x27, 0x61, 0x64, 0xe7, 0x66, 0x0c, 0x74, 0x07, 0x9a, 0x8b, 0x19,
	0x8b, 0xe9, 0x9b, 0x64, 0x3e, 0xa1, 0xdc, 0x4e, 0x2f, 0x0f, 0xa1, 0x6f, 0xa0, 0x2a, 0x98, 0x17,
	0x92, 0xa8, 0x5b, 0xb9, 0x53, 0xbe, 0xdf, 0xdc, 0xbb, 0xb7, 0xa6, 0x58, 0xfb, 0x63, 0xcd, 0xda,
	0xf7, 0x74, 0xb3, 0xc6, 0x36, 0xc8, 0x7d, 0x0b, 0xed, 0x82, 0x43, 0x67, 0xe2, 0x72, 0x91, 0x4e,
	0x4f, 0x3f, 0xab, 0xed, 0x9f, 0x08, 0xca, 0x73, 0xed, 0x22, 0xb3, 0xd5, 0xbc, 0x17, 0x9c, 0xb1,
	0xa9, 0x9d, 0x9b, 0x31, 0xdc, 0x7f, 0x38, 0xd0, 0xca, 0xd7, 0x91, 0x4a, 0xd7, 0x94, 0x45, 0x11,
	0x3b, 0xa7, 0x7c, 0xa0, 0xc6, 0xd1, 0xef, 0x6f, 0xe3, 0x22, 0x88, 0x76, 0x61, 0xcb, 0x00, 0x61,
	0x1c, 0x18, 0x5a, 0x49, 0xd3, 0x56, 0x50, 0xd4, 0x83, 0x96, 0xed, 0xf0, 0x86, 0x55, 0xd6, 0xac,
	0x02, 0xa6, 0x52, 0xa7, 0x1a, 0x79, 0x4a, 0xa9, 0x68, 0x4a, 0x1e, 0xd2, 0x45, 0xcd, 0x84, 0x34,
	0xfe, 0x4d, 0xed, 0x5f, 0x02, 0x6a, 0xc6, 0xe4, 0x8c, 0x72, 0x12, 0x50, 0xac, 0x63, 0x74, 0xfb,
	0x2a, 0xe1, 0x22, 0xe8, 0xfe, 0xde, 0x81, 0x66, 0x6e, 0x9b, 0xe9, 0xf4, 0x85, 0xf1, 0x65, 0x96,
	0xbe, 0x30, 0xbe, 0x54, 0x29, 0x12, 0x73, 0x12, 0x65, 0x4b, 0xab, 0x0d, 0xd5, 0xe1, 0xe6, 0xd4,
	0x0f, 0x93, 0x79, 0xda, 0x6b, 0x8d, 0xa5, 0xd8, 0x11, 0xe1, 0x01, 0xb5, 0x25, 0x67, 0x0c, 0xb5,
	0x04, 0x8c, 0x87, 0x41, 0x18, 0x93, 0xc8, 0x56, 0x5a, 0x66, 0x2b, 0x9f, 0x4a, 0xb4, 0x5e, 0x1e,
	0xd3, 0x63, 0x33, 0xdb, 0xfd, 0x6b, 0x19, 0xda, 0x85, 0x8e, 0xa7, 0xf2, 0xe2, 0xe7, 0x9a, 0xb2,
	0x99, 0x68, 0x1e, 0x42, 0x7d, 0x40, 0x92, 0xf2, 0xb9, 0xd8, 0x8f, 0xfd, 0x01, 0x8b, 0xfd, 0x50,
	0x81, 0xc2, 0x4e, 0xfe, 0x1a, 0x8f, 0xca, 0x63, 0x44, 0xe2, 0x20, 0x21, 0x01, 0x15, 0xdd, 0xb2,
	0xde, 0xf1, 0x4b, 0x40, 0xbd, 0x8d, 0x78, 0x1e, 0x5d, 0x48, 0xea, 0x0f, 0x12, 0xce, 0x69, 0xec,
	0x85, 0x54, 0xe8, 0x62, 0x6d, 0xe0, 0x6b, 0x3c, 0xe8, 0xa7, 0x50, 0x9e, 0x52, 0xaa, 0x3f, 0xb2,
	0xb9, 0xb7, 0xbb, 0xb6, 0x73, 0x2f, 0xad, 0x43, 0x4a, 0xb1, 0x0a, 0x71, 0xff, 0xe9, 0x40, 0x2b,
	0x8f, 0xa2, 0x07, 0x2a, 0x31, 0x17, 0xd4, 0x3f, 0xa4, 0xa9, 0xac, 0xd8, 0xea, 0xdb, 0x91, 0x2e,
	0xdf, 0x91, 0x28, 0xa1, 0x38, 0xf3, 0xa3, 0x2f, 0x01, 0x16, 0x94, 0x7b, 0x34, 0x96, 0x24, 0x30,
	0x55, 0x5e, 0xc2, 0x39, 0x04, 0x1d, 0x41, 0x6d, 0x4a, 0xe9, 0xa9, 0xda, 0x1a, 0x6a, 0xbd, 0xb6,
	0xf6, 0xfa, 0xff, 0xdb, 0xd4, 0xfa, 0x87, 0x26, 0x0a, 0xa7, 0xe1, 0xbd, 0x43, 0xa8, 0x59, 0x0c,
	0xb5, 0xa0, 0x7e, 0x68, 0x27, 0xd0, 0xd9, 0x40, 0x3b, 0xd0, 0x3e, 0xc9, 0x06, 0x54, 0x90, 0x83,
	0x5c, 0xb8, 0xa5, 0x09, 0x27, 0x51, 0x22, 0x8a, 0xbe, 0x52, 0xef, 0x3f, 0x9f, 0x41, 0xcd, 0x4a,
	0x1e, 0x55, 0x76, 0x22, 0x4a, 0x82, 0xb4, 0xec, 0xd4, 0x33, 0xba, 0x0d, 0x75, 0x73, 0x68, 0x8e,
	0x86, 0x56, 0x2b, 0x95, 0xfb, 0xa3, 0x21, 0xce, 0x40, 0xf4, 0x08, 0xea, 0x73, 0x2a, 0x89, 0x12,
	0x39, 0x56, 0x1a, 0xdd, 0x54, 0xdf, 0x64, 0xdf, 0xd9, 0x7f, 0x6d, 0x7d, 0x38, 0x63, 0xa1, 0xbb,
	0x50, 0x09, 0x25, 0x9d, 0xeb, 0xd2, 0x6c, 0xee, 0x75, 0xf2, 0xec, 0x91, 0xa4, 0x73, 0xac, 0xbd,
	0x68, 0x08, 0xdb, 0x62, 0x16, 0x2e, 0x16, 0x61, 0x1c, 0x1c, 0x2f, 0x4c, 0xf1, 0x6c, 0xea, 0xde,
	0xe4, 0xe6, 0x03, 0xc6, 0x05, 0x0a, 0x5e, 0x0d, 0x41, 0xf7, 0x60, 0x53, 0x92, 0x0b, 0x2a, 0xba,
	0x55, 0x1d, 0xbb, 0x9d, 0x8f, 0x3d, 0x25, 0x17, 0xd8, 0x78, 0xd1, 0x43, 0xa8, 0x79, 0x2c, 0x51,
	0xb2, 0xa7, 0x5b, 0xd3, 0x44, 0x94, 0x27, 0x0e, 0xb4, 0x0b, 0xa7, 0x14, 0xb5, 0xca, 0xd9, 0x81,
	0x2f, 0xba, 0x75, 0x5d, 0x84, 0x39, 0x64, 0x4d, 0xe9, 0x37, 0xd6, 0x96, 0x7e, 0x0f, 0x5a, 0x9c,
	0x4e, 0x93, 0xd8, 0x3f, 0x61, 0x51, 0xe8, 0x5d, 0x6a, 0xbd, 0xd1, 0xc0, 0x05, 0xcc, 0xfd, 0x5d,
	0x05, 0xea, 0x69, 0x2e, 0xd5, 0x01, 0xa0, 0x8e, 0xbe, 0x74, 0xe7, 0xb5, 0x71, 0x6a, 0xa2, 0x03,
	0x68, 0x29, 0x39, 0xc1, 0x89, 0x27, 0x75, 0x95, 0x95, 0x74, 0x95, 0xfd, 0xe0, 0xba, 0x15, 0xd1,
	0x7d, 0x3d, 0x25, 0xe2, 0x42, 0x18, 0x7a, 0x02, 0xd5, 0x29, 0xe3, 0x73, 0x22, 0x6d, 0x99, 0xfe,
	0xdf, 0xb5, 0x2f, 0x38, 0xd4, 0x14, 0x6c, 0xa9, 0x68, 0x0f, 0xaa, 0x5a, 0xf8, 0x5e, 0xda, 0x95,
	0xfd, 0xd8, 0x11, 0x6c, 0x99, 0x6b, 0xf6, 0xf5, 0xe6, 0xda, 0x7d, 0xad, 0x34, 0xa4, 0x6d, 0x0a,
	0x69, 0x97, 0x4a, 0x6d, 0xf5, 0x2e, 0xd5, 0x7f, 0xd8, 0xb9, 0x1a, 0x86, 0x25, 0xf2, 0x88, 0x25,
	0x5c, 0x68, 0x3d, 0xd8, 0xc6, 0xd7, 0x78, 0xd0, 0x13, 0xd8, 0x5e, 0xf0, 0xd0, 0x53, 0x9d, 0xdc,
	0x6e, 0x67, 0xbd, 0x46, 0xcd, 0xbd, 0x46, 0xb6, 0xbf, 0xf1, 0x2a, 0xa3, 0xe7, 0x43, 0x2b, 0x9f,
	0x37, 0xbd, 0xdd, 0x8e, 0xde, 0x8f, 0x47, 0x83, 0xfd, 0x57, 0xdf, 0x7d, 0x7b, 0x7c, 0x3c, 0xec,
	0x6c, 0xa0, 0x0e, 0xb4, 0x86, 0xa3, 0x6f, 0x47, 0xa7, 0x29, 0xe2, 0xa0, 0x26, 0xd4, 0xc6, 0x07,
	0xf8, 0xdd, 0x68, 0x70, 0xd0, 0x29, 0xa1, 0x2d, 0x80, 0xc1, 0xab, 0xfd, 0xf1, 0x78, 0x74, 0x38,
	0x3a, 0x18, 0x76, 0xca, 0x08, 0xc1, 0xd6, 0x00, 0xbf, 0x3f, 0x39, 0x3d, 0x1e, 0xbc, 0xc5, 0xf8,
	0xe0, 0xcd, 0xe0, 0x7d, 0xa7, 0xd2, 0xfb, 0x21, 0x54, 0x4d, 0x72, 0xd1, 0x36, 0x34, 0x0f, 0x47,
	0xbf, 0x3c, 0x18, 0x7e, 0x77, 0x82, 0x55, 0xb8, 0x7e, 0xfb, 0xeb, 0x7d, 0xfc, 0xf2, 0xe0, 0xd4,
	0x22, 0x8e, 0xfb, 0xe7, 0x3a, 0x54, 0xd4, 0xc6, 0x51, 0x4d, 0x5f, 0x86, 0x32, 0x4a, 0x8f, 0x5d,
	0x63, 0xac, 0xb6, 0xea, 0xd2, 0xd5, 0x56, 0xbd, 0x0b, 0x5b, 0x0b, 0xce, 0x3c, 0x2a, 0x44, 0x18,
	0x07, 0x2a, 0x45, 0xf6, 0x30, 0x59, 0x41, 0x33, 0x89, 0x5d, 0xc9, 0x49, 0x6c, 0x75, 0x54, 0x91,
	0x20, 0x5d, 0x32, 0xfd, 0x8c, 0xfa, 0x50, 0x0d, 0xe7, 0xba, 0x8f, 0x9b, 0x5d, 0x77, 0x6b, 0x75,
	0x8b, 0x1b, 0x4d, 0x89, 0x2d, 0x4b, 0xed, 0x27, 0x8f, 0x48, 0x1a, 0x30, 0xae, 0x16, 0xbf, 0x66,
	0xf6, 0xd3, 0x12, 0x51, 0xdf, 0x15, 0x70, 0x32, 0x17, 0x5a, 0xc5, 0x97, 0xb0, 0x31, 0xd4, 0x81,
	0xe1, 0xa5, 0x7b, 0xc8, 0x6e, 0xae, 0x25, 0x80, 0x1e, 0x43, 0x8d, 0xd9, 0xb6, 0x01, 0x7a, 0x12,
	0x9f, 0x5f, 0x99, 0x84, 0xed, 0x19, 0x29, 0x0f, 0xdd, 0x87, 0x8a, 0xf8, 0x90, 0x88, 0x6e, 0x53,
	0xf3, 0x6f, 0x5e, 0xe1, 0x8f, 0x3f, 0x24, 0x58, 0x33, 0x8c, 0x5c, 0x09, 0x3d, 0xaa, 0x45, 0xba,
	0x96, 0x2b, 0xa1, 0x47, 0xd1, 0xcf, 0xe1, 0x0b, 0x8f, 0x5f, 0x2e, 0x24, 0xb3, 0x51, 0x69, 0xcd,
	0x0c, 0x98, 0x4f, 0xb5, 0x2a, 0x6f, 0xe0, 0xf5, 0x04, 0xf4, 0x1c, 0xdc, 0x82, 0xf3, 0x44, 0xbd,
	0xd3, 0x8a, 0x54, 0xae, 0x75, 0x79, 0x09, 0x7f, 0x84, 0xe1, 0xfe, 0xc5, 0x81, 0xea, 0xf1, 0xf2,
	0xaf, 0x90, 0x3a, 0xc6, 0x9d, 0xdc, 0x9f, 0xb2, 0x4f, 0x57, 0xc1, 0x33, 0xa8, 0x9f, 0x11, 0x1e,
	0x92, 0x58, 0x9a, 0xf3, 0xb7, 0xb9, 0x77, 0x7b, 0x4d, 0xca, 0xfa, 0xef, 0x0c, 0x0f, 0x67, 0x01,
	0xee, 0x4b, 0xa8, 0x59, 0xf0, 0xda, 0xd1, 0x1f, 0xc2, 0xa6, 0x5e, 0x6b, 0x7b, 0x84, 0xac, 0x2b,
	0x08, 0x43, 0x72, 0xff, 0xe6, 0x40, 0x79, 0xfc, 0x21, 0x41, 0xcf, 0x01, 0x04, 0x8d, 0xa8, 0x67,
	0x96, 0xd1, 0xd1, 0x73, 0xfa, 0xf2, 0xba, 0x65, 0xe9, 0x8f, 0x53, 0x1a, 0xce, 0x45, 0x68, 0x69,
	0xc6, 0x99, 0x9f, 0x78, 0xd2, 0x1e, 0x5e, 0xea, 0xff, 0x46, 0x0a, 0xa8, 0x56, 0xf2, 0x7d, 0x42,
	0x62, 0x19, 0xca, 0x4b, 0x5b, 0xef, 0x99, 0xad, 0x75, 0x7e, 0xc2, 0xbd, 0x59, 0x4e, 0x42, 0x2d,
	0x01, 0xf7, 0x1b, 0x68, 0x64, 0x03, 0x2a, 0x05, 0xc6, 0xf2, 0x22, 0xc8, 0x5a, 0xba, 0x47, 0x9b,
	0x8c, 0xd8, 0xa1, 0x53, 0xd3, 0xfd, 0xad, 0x03, 0x9b, 0xfa, 0x7b, 0x0b, 0x9a, 0xcb, 0x29, 0x6a,
	0xae, 0x82, 0x56, 0x2b, 0xad, 0x68, 0xb5, 0x4c, 0xdd, 0x95, 0xf3, 0xea, 0x6e, 0xa9, 0x05, 0x2b,
	0xab, 0x5a, 0xd0, 0x28, 0xc7, 0xcd, 0xbc, 0x72, 0x4c, 0x35, 0x66, 0x75, 0xa9, 0x31, 0xdd, 0x5f,
	0x97, 0x61, 0xab, 0x78, 0xa2, 0x5e, 0xbb, 0x9a, 0xcf, 0xac, 0xba, 0x37, 0x87, 0xcb, 0x57, 0xeb,
	0xcf, 0xe3, 0xcc, 0xd4, 0x47, 0x8c, 0xf9, 0x1b, 0xb0, 0x0b, 0x35, 0x4e, 0x03, 0xbd, 0xa2, 0xaa,
	0xca, 0xb6, 0xf6, 0x5a, 0xfd, 0x81, 0xb9, 0xf9, 0x51, 0xdb, 0x00, 0xa7, 0x4e, 0xf4, 0x1c, 0xea,
	0x82, 0xf2, 0xb3, 0xd0, 0xb3, 0x3a, 0xaf, 0xb9, 0xd7, 0xfb, 0xd8, 0x40, 0x86, 0x8a, 0xb3, 0x18,
	0xf7, 0x37, 0x0e, 0xd4, 0x2c, 0xba, 0xa6, 0x24, 0x77, 0xa8, 0x90, 0xe1, 0x9c, 0x48, 0xea, 0x0f,
	0x69, 0x14, 0x9e, 0xd1, 0xec, 0x2f, 0xdd, 0x55, 0xc7, 0x72, 0xc7, 0x97, 0xf3, 0x3b, 0xfe, 0x11,
	0xdc, 0x20, 0xbe, 0x69, 0x38, 0x24, 0x52, 0xc5, 0xa8, 0xb7, 0xa4, 0x4d, 0xff, 0x75, 0xae, 0xde,
	0x63, 0x68, 0xe5, 0x73, 0xa2, 0xba, 0xf9, 0xab, 0x63, 0x75, 0x76, 0x9c, 0x8c, 0x06, 0x2f, 0xdf,
	0x9e, 0x74, 0x36, 0x56, 0x1b, 0xbe, 0xe3, 0xfe, 0xca, 0x81, 0xf2, 0x29, 0xb9, 0x50, 0x05, 0x25,
	0xc9, 0xc5, 0xe9, 0xf2, 0x6f, 0x55, 0x6a, 0xa2, 0x87, 0x00, 0x92, 0x5c, 0x60, 0x9b, 0xd5, 0xd2,
	0x35, 0x59, 0xcd, 0xf9, 0x55, 0x27, 0x90, 0xe4, 0x22, 0x9d, 0x85, 0xfe, 0xa0, 0x3a, 0xce, 0x43,
	0x2b, 0x2a, 0xb6, 0xb2, 0xaa, 0x62, 0xdd, 0x3f, 0x39, 0x50, 0x35, 0x9a, 0x68, 0xcd, 0x91, 0x73,
	0x13, 0x2a, 0x33, 0x22, 0x66, 0x26, 0x9d, 0x47, 0x1b, 0x58, 0x5b, 0xe8, 0x2e, 0xb4, 0xfc, 0x50,
	0xe8, 0x3f, 0x88, 0xba, 0x25, 0x96, 0xad, 0xb7, 0x80, 0xa2, 0x07, 0xb0, 0x6d, 0x87, 0x1a, 0x5a,
	0xd8, 0xcc, 0xe0, 0xc8, 0xc1, 0xab, 0x0e, 0xb4, 0x0b, 0x6d, 0xbd, 0x10, 0x19, 0x53, 0x57, 0xf8,
	0x91, 0x83, 0x8b, 0xf0, 0x8b, 0x2a, 0x54, 0x3c, 0xe6, 0xd3, 0x17, 0x00, 0xf5, 0x74, 0xac, 0xde,
	0x14, 0xda, 0x85, 0x0b, 0x3f, 0x74, 0x6f, 0x79, 0x29, 0x98, 0xbb, 0x3d, 0xb4, 0xde, 0xe5, 0x65,
	0x60, 0x07, 0xca, 0x5e, 0xe8, 0xdb, 0x4a, 0x51, 0x8f, 0xba, 0x59, 0x84, 0x41, 0x4c, 0x64, 0xc2,
	0xcd, 0x47, 0xb5, 0xf0, 0x12, 0xd8, 0xfb, 0x97, 0x03, 0x0d, 0x36, 0xb1, 0x17, 0xa2, 0xe8, 0x09,
	0x34, 0xb2, 0x3b, 0x4c, 0xa4, 0x8f, 0x98, 0xd5, 0x2b, 0x4d, 0xb7, 0xa5, 0xd0, 0xf4, 0x4e, 0xb3,
	0xb7, 0xf1, 0xc8, 0x41, 0x4f, 0xa1, 0x91, 0xdd, 0x09, 0x9a, 0xa0, 0xd5, 0xab, 0x44, 0xf7, 0xb3,
	0x15, 0xd4, 0x5e, 0xe1, 0x6d, 0xa0, 0x1f, 0x43, 0xcd, 0x5e, 0x0a, 0x22, 0xad, 0x69, 0x8b, 0xf7,
	0x88, 0xee, 0x8d, 0x02, 0x96, 0x45, 0x3d, 0x85, 0x46, 0x76, 0x1f, 0x68, 0x46, 0x5c, 0xbd, 0x46,
	0x34, 0x23, 0x5e, 0xbd, 0x34, 0xdc, 0x98, 0x54, 0xb5, 0xdc, 0x7b, 0xf2, 0xdf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x52, 0x3f, 0x09, 0xe1, 0x05, 0x16, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObcrawlerClient is the client API for Obcrawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObcrawlerClient interface {
	// Subscribe is an RPC which streams new profiles and listings as they
	// are crawled. Note you should subscribe to this as soon as the crawler
	// starts as any data that is crawled while not subscribed will not be
	// resent until the node is crawled again.
	//
	// Also, search engines MUST respect the expiration and not return any
	// data which has expired.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Obcrawler_SubscribeClient, error)
	// CrawlNode queues up a crawl of the given node.
	CrawlNode(ctx context.Context, in *CrawlNodeRequest, opts ...grpc.CallOption) (*CrawlNodeResponse, error)
	// BanNode will prevent the node from being crawled in the future as
	// well as purge all cached/pinned files of this node from the crawler.
	BanNode(ctx context.Context, in *BanNodeRequest, opts ...grpc.CallOption) (*BanNodeResponse, error)
	// UnbanNode will un-ban the provided node. It will not immediately
	// crawl the node again. If you want that call CrawlNode.
	UnbanNode(ctx context.Context, in *UnbanNodeRequest, opts ...grpc.CallOption) (*UnbanNodeResponse, error)
}

type obcrawlerClient struct {
	cc *grpc.ClientConn
}

func NewObcrawlerClient(cc *grpc.ClientConn) ObcrawlerClient {
	return &obcrawlerClient{cc}
}

func (c *obcrawlerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Obcrawler_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Obcrawler_serviceDesc.Streams[0], "/pb.obcrawler/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &obcrawlerSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Obcrawler_SubscribeClient interface {
	Recv() (*UserData, error)
	grpc.ClientStream
}

type obcrawlerSubscribeClient struct {
	grpc.ClientStream
}

func (x *obcrawlerSubscribeClient) Recv() (*UserData, error) {
	m := new(UserData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *obcrawlerClient) CrawlNode(ctx context.Context, in *CrawlNodeRequest, opts ...grpc.CallOption) (*CrawlNodeResponse, error) {
	out := new(CrawlNodeResponse)
	err := c.cc.Invoke(ctx, "/pb.obcrawler/CrawlNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obcrawlerClient) BanNode(ctx context.Context, in *BanNodeRequest, opts ...grpc.CallOption) (*BanNodeResponse, error) {
	out := new(BanNodeResponse)
	err := c.cc.Invoke(ctx, "/pb.obcrawler/BanNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obcrawlerClient) UnbanNode(ctx context.Context, in *UnbanNodeRequest, opts ...grpc.CallOption) (*UnbanNodeResponse, error) {
	out := new(UnbanNodeResponse)
	err := c.cc.Invoke(ctx, "/pb.obcrawler/UnbanNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObcrawlerServer is the server API for Obcrawler service.
type ObcrawlerServer interface {
	// Subscribe is an RPC which streams new profiles and listings as they
	// are crawled. Note you should subscribe to this as soon as the crawler
	// starts as any data that is crawled while not subscribed will not be
	// resent until the node is crawled again.
	//
	// Also, search engines MUST respect the expiration and not return any
	// data which has expired.
	Subscribe(*SubscribeRequest, Obcrawler_SubscribeServer) error
	// CrawlNode queues up a crawl of the given node.
	CrawlNode(context.Context, *CrawlNodeRequest) (*CrawlNodeResponse, error)
	// BanNode will prevent the node from being crawled in the future as
	// well as purge all cached/pinned files of this node from the crawler.
	BanNode(context.Context, *BanNodeRequest) (*BanNodeResponse, error)
	// UnbanNode will un-ban the provided node. It will not immediately
	// crawl the node again. If you want that call CrawlNode.
	UnbanNode(context.Context, *UnbanNodeRequest) (*UnbanNodeResponse, error)
}

// UnimplementedObcrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedObcrawlerServer struct {
}

func (*UnimplementedObcrawlerServer) Subscribe(req *SubscribeRequest, srv Obcrawler_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedObcrawlerServer) CrawlNode(ctx context.Context, req *CrawlNodeRequest) (*CrawlNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlNode not implemented")
}
func (*UnimplementedObcrawlerServer) BanNode(ctx context.Context, req *BanNodeRequest) (*BanNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BanNode not implemented")
}
func (*UnimplementedObcrawlerServer) UnbanNode(ctx context.Context, req *UnbanNodeRequest) (*UnbanNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbanNode not implemented")
}

func RegisterObcrawlerServer(s *grpc.Server, srv ObcrawlerServer) {
	s.RegisterService(&_Obcrawler_serviceDesc, srv)
}

func _Obcrawler_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObcrawlerServer).Subscribe(m, &obcrawlerSubscribeServer{stream})
}

type Obcrawler_SubscribeServer interface {
	Send(*UserData) error
	grpc.ServerStream
}

type obcrawlerSubscribeServer struct {
	grpc.ServerStream
}

func (x *obcrawlerSubscribeServer) Send(m *UserData) error {
	return x.ServerStream.SendMsg(m)
}

func _Obcrawler_CrawlNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObcrawlerServer).CrawlNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.obcrawler/CrawlNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObcrawlerServer).CrawlNode(ctx, req.(*CrawlNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obcrawler_BanNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObcrawlerServer).BanNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.obcrawler/BanNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObcrawlerServer).BanNode(ctx, req.(*BanNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obcrawler_UnbanNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObcrawlerServer).UnbanNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.obcrawler/UnbanNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObcrawlerServer).UnbanNode(ctx, req.(*UnbanNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Obcrawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.obcrawler",
	HandlerType: (*ObcrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlNode",
			Handler:    _Obcrawler_CrawlNode_Handler,
		},
		{
			MethodName: "BanNode",
			Handler:    _Obcrawler_BanNode_Handler,
		},
		{
			MethodName: "UnbanNode",
			Handler:    _Obcrawler_UnbanNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Obcrawler_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crawler.proto",
}
