// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile_ModeratorInfo_ModeratorFee_FeeType int32

const (
	Profile_ModeratorInfo_ModeratorFee_FixedFee               Profile_ModeratorInfo_ModeratorFee_FeeType = 0
	Profile_ModeratorInfo_ModeratorFee_PercentageFee          Profile_ModeratorInfo_ModeratorFee_FeeType = 1
	Profile_ModeratorInfo_ModeratorFee_FixedPlusPercentageFee Profile_ModeratorInfo_ModeratorFee_FeeType = 2
)

var Profile_ModeratorInfo_ModeratorFee_FeeType_name = map[int32]string{
	0: "FixedFee",
	1: "PercentageFee",
	2: "FixedPlusPercentageFee",
}

var Profile_ModeratorInfo_ModeratorFee_FeeType_value = map[string]int32{
	"FixedFee":               0,
	"PercentageFee":          1,
	"FixedPlusPercentageFee": 2,
}

func (x Profile_ModeratorInfo_ModeratorFee_FeeType) String() string {
	return proto.EnumName(Profile_ModeratorInfo_ModeratorFee_FeeType_name, int32(x))
}

func (Profile_ModeratorInfo_ModeratorFee_FeeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 4, 0, 0}
}

// RPC MESSAGES
type SubscribeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

type UserData struct {
	// Types that are valid to be assigned to Data:
	//	*UserData_Profile
	//	*UserData_Listing
	Data                 isUserData_Data      `protobuf_oneof:"data"`
	Expiration           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expiration,proto3" json:"expiration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{1}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

type isUserData_Data interface {
	isUserData_Data()
}

type UserData_Profile struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile,proto3,oneof"`
}

type UserData_Listing struct {
	Listing *SignedListing `protobuf:"bytes,2,opt,name=listing,proto3,oneof"`
}

func (*UserData_Profile) isUserData_Data() {}

func (*UserData_Listing) isUserData_Data() {}

func (m *UserData) GetData() isUserData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UserData) GetProfile() *Profile {
	if x, ok := m.GetData().(*UserData_Profile); ok {
		return x.Profile
	}
	return nil
}

func (m *UserData) GetListing() *SignedListing {
	if x, ok := m.GetData().(*UserData_Listing); ok {
		return x.Listing
	}
	return nil
}

func (m *UserData) GetExpiration() *timestamp.Timestamp {
	if m != nil {
		return m.Expiration
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*UserData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*UserData_Profile)(nil),
		(*UserData_Listing)(nil),
	}
}

type CrawlNodeRequest struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlNodeRequest) Reset()         { *m = CrawlNodeRequest{} }
func (m *CrawlNodeRequest) String() string { return proto.CompactTextString(m) }
func (*CrawlNodeRequest) ProtoMessage()    {}
func (*CrawlNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{2}
}

func (m *CrawlNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlNodeRequest.Unmarshal(m, b)
}
func (m *CrawlNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlNodeRequest.Marshal(b, m, deterministic)
}
func (m *CrawlNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlNodeRequest.Merge(m, src)
}
func (m *CrawlNodeRequest) XXX_Size() int {
	return xxx_messageInfo_CrawlNodeRequest.Size(m)
}
func (m *CrawlNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlNodeRequest proto.InternalMessageInfo

func (m *CrawlNodeRequest) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type CrawlNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CrawlNodeResponse) Reset()         { *m = CrawlNodeResponse{} }
func (m *CrawlNodeResponse) String() string { return proto.CompactTextString(m) }
func (*CrawlNodeResponse) ProtoMessage()    {}
func (*CrawlNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{3}
}

func (m *CrawlNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrawlNodeResponse.Unmarshal(m, b)
}
func (m *CrawlNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrawlNodeResponse.Marshal(b, m, deterministic)
}
func (m *CrawlNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrawlNodeResponse.Merge(m, src)
}
func (m *CrawlNodeResponse) XXX_Size() int {
	return xxx_messageInfo_CrawlNodeResponse.Size(m)
}
func (m *CrawlNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrawlNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrawlNodeResponse proto.InternalMessageInfo

type BanNodeRequest struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BanNodeRequest) Reset()         { *m = BanNodeRequest{} }
func (m *BanNodeRequest) String() string { return proto.CompactTextString(m) }
func (*BanNodeRequest) ProtoMessage()    {}
func (*BanNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{4}
}

func (m *BanNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BanNodeRequest.Unmarshal(m, b)
}
func (m *BanNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BanNodeRequest.Marshal(b, m, deterministic)
}
func (m *BanNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BanNodeRequest.Merge(m, src)
}
func (m *BanNodeRequest) XXX_Size() int {
	return xxx_messageInfo_BanNodeRequest.Size(m)
}
func (m *BanNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BanNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BanNodeRequest proto.InternalMessageInfo

func (m *BanNodeRequest) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type BanNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BanNodeResponse) Reset()         { *m = BanNodeResponse{} }
func (m *BanNodeResponse) String() string { return proto.CompactTextString(m) }
func (*BanNodeResponse) ProtoMessage()    {}
func (*BanNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{5}
}

func (m *BanNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BanNodeResponse.Unmarshal(m, b)
}
func (m *BanNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BanNodeResponse.Marshal(b, m, deterministic)
}
func (m *BanNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BanNodeResponse.Merge(m, src)
}
func (m *BanNodeResponse) XXX_Size() int {
	return xxx_messageInfo_BanNodeResponse.Size(m)
}
func (m *BanNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BanNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BanNodeResponse proto.InternalMessageInfo

type UnbanNodeRequest struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbanNodeRequest) Reset()         { *m = UnbanNodeRequest{} }
func (m *UnbanNodeRequest) String() string { return proto.CompactTextString(m) }
func (*UnbanNodeRequest) ProtoMessage()    {}
func (*UnbanNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{6}
}

func (m *UnbanNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbanNodeRequest.Unmarshal(m, b)
}
func (m *UnbanNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbanNodeRequest.Marshal(b, m, deterministic)
}
func (m *UnbanNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbanNodeRequest.Merge(m, src)
}
func (m *UnbanNodeRequest) XXX_Size() int {
	return xxx_messageInfo_UnbanNodeRequest.Size(m)
}
func (m *UnbanNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbanNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbanNodeRequest proto.InternalMessageInfo

func (m *UnbanNodeRequest) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

type UnbanNodeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbanNodeResponse) Reset()         { *m = UnbanNodeResponse{} }
func (m *UnbanNodeResponse) String() string { return proto.CompactTextString(m) }
func (*UnbanNodeResponse) ProtoMessage()    {}
func (*UnbanNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{7}
}

func (m *UnbanNodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbanNodeResponse.Unmarshal(m, b)
}
func (m *UnbanNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbanNodeResponse.Marshal(b, m, deterministic)
}
func (m *UnbanNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbanNodeResponse.Merge(m, src)
}
func (m *UnbanNodeResponse) XXX_Size() int {
	return xxx_messageInfo_UnbanNodeResponse.Size(m)
}
func (m *UnbanNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbanNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnbanNodeResponse proto.InternalMessageInfo

// DATA MESSAGES
type Profile struct {
	PeerID                 string                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Handle                 string                 `protobuf:"bytes,3,opt,name=handle,proto3" json:"handle,omitempty"`
	Location               string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	About                  string                 `protobuf:"bytes,5,opt,name=about,proto3" json:"about,omitempty"`
	ShortDescription       string                 `protobuf:"bytes,6,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Nsfw                   bool                   `protobuf:"varint,7,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Vendor                 bool                   `protobuf:"varint,8,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Moderator              bool                   `protobuf:"varint,9,opt,name=moderator,proto3" json:"moderator,omitempty"`
	ModeratorInfo          *Profile_ModeratorInfo `protobuf:"bytes,10,opt,name=moderatorInfo,proto3" json:"moderatorInfo,omitempty"`
	ContactInfo            *Profile_ContactInfo   `protobuf:"bytes,11,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	Colors                 *Profile_ProfileColors `protobuf:"bytes,12,opt,name=colors,proto3" json:"colors,omitempty"`
	AvatarHashes           *Profile_ImageHashes   `protobuf:"bytes,13,opt,name=avatarHashes,proto3" json:"avatarHashes,omitempty"`
	HeaderHashes           *Profile_ImageHashes   `protobuf:"bytes,14,opt,name=headerHashes,proto3" json:"headerHashes,omitempty"`
	Stats                  *Profile_ProfileStats  `protobuf:"bytes,15,opt,name=stats,proto3" json:"stats,omitempty"`
	PublicKey              string                 `protobuf:"bytes,16,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	StoreAndForwardServers []string               `protobuf:"bytes,17,rep,name=storeAndForwardServers,proto3" json:"storeAndForwardServers,omitempty"`
	LastModified           *timestamp.Timestamp   `protobuf:"bytes,18,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}               `json:"-"`
	XXX_unrecognized       []byte                 `json:"-"`
	XXX_sizecache          int32                  `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Profile) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Profile) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Profile) GetVendor() bool {
	if m != nil {
		return m.Vendor
	}
	return false
}

func (m *Profile) GetModerator() bool {
	if m != nil {
		return m.Moderator
	}
	return false
}

func (m *Profile) GetModeratorInfo() *Profile_ModeratorInfo {
	if m != nil {
		return m.ModeratorInfo
	}
	return nil
}

func (m *Profile) GetContactInfo() *Profile_ContactInfo {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Profile) GetColors() *Profile_ProfileColors {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *Profile) GetAvatarHashes() *Profile_ImageHashes {
	if m != nil {
		return m.AvatarHashes
	}
	return nil
}

func (m *Profile) GetHeaderHashes() *Profile_ImageHashes {
	if m != nil {
		return m.HeaderHashes
	}
	return nil
}

func (m *Profile) GetStats() *Profile_ProfileStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Profile) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

func (m *Profile) GetStoreAndForwardServers() []string {
	if m != nil {
		return m.StoreAndForwardServers
	}
	return nil
}

func (m *Profile) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

type Profile_ProfileColors struct {
	Primary              string   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary            string   `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Highlight            string   `protobuf:"bytes,4,opt,name=highlight,proto3" json:"highlight,omitempty"`
	HighlightText        string   `protobuf:"bytes,5,opt,name=highlightText,proto3" json:"highlightText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ProfileColors) Reset()         { *m = Profile_ProfileColors{} }
func (m *Profile_ProfileColors) String() string { return proto.CompactTextString(m) }
func (*Profile_ProfileColors) ProtoMessage()    {}
func (*Profile_ProfileColors) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 0}
}

func (m *Profile_ProfileColors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ProfileColors.Unmarshal(m, b)
}
func (m *Profile_ProfileColors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ProfileColors.Marshal(b, m, deterministic)
}
func (m *Profile_ProfileColors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ProfileColors.Merge(m, src)
}
func (m *Profile_ProfileColors) XXX_Size() int {
	return xxx_messageInfo_Profile_ProfileColors.Size(m)
}
func (m *Profile_ProfileColors) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ProfileColors.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ProfileColors proto.InternalMessageInfo

func (m *Profile_ProfileColors) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Profile_ProfileColors) GetSecondary() string {
	if m != nil {
		return m.Secondary
	}
	return ""
}

func (m *Profile_ProfileColors) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Profile_ProfileColors) GetHighlight() string {
	if m != nil {
		return m.Highlight
	}
	return ""
}

func (m *Profile_ProfileColors) GetHighlightText() string {
	if m != nil {
		return m.HighlightText
	}
	return ""
}

type Profile_ContactInfo struct {
	Website              string                               `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Email                string                               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                               `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Social               []*Profile_ContactInfo_SocialAccount `protobuf:"bytes,4,rep,name=social,proto3" json:"social,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *Profile_ContactInfo) Reset()         { *m = Profile_ContactInfo{} }
func (m *Profile_ContactInfo) String() string { return proto.CompactTextString(m) }
func (*Profile_ContactInfo) ProtoMessage()    {}
func (*Profile_ContactInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 1}
}

func (m *Profile_ContactInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ContactInfo.Unmarshal(m, b)
}
func (m *Profile_ContactInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ContactInfo.Marshal(b, m, deterministic)
}
func (m *Profile_ContactInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ContactInfo.Merge(m, src)
}
func (m *Profile_ContactInfo) XXX_Size() int {
	return xxx_messageInfo_Profile_ContactInfo.Size(m)
}
func (m *Profile_ContactInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ContactInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ContactInfo proto.InternalMessageInfo

func (m *Profile_ContactInfo) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile_ContactInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile_ContactInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile_ContactInfo) GetSocial() []*Profile_ContactInfo_SocialAccount {
	if m != nil {
		return m.Social
	}
	return nil
}

type Profile_ContactInfo_SocialAccount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Proof                string   `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ContactInfo_SocialAccount) Reset()         { *m = Profile_ContactInfo_SocialAccount{} }
func (m *Profile_ContactInfo_SocialAccount) String() string { return proto.CompactTextString(m) }
func (*Profile_ContactInfo_SocialAccount) ProtoMessage()    {}
func (*Profile_ContactInfo_SocialAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 1, 0}
}

func (m *Profile_ContactInfo_SocialAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ContactInfo_SocialAccount.Unmarshal(m, b)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ContactInfo_SocialAccount.Marshal(b, m, deterministic)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ContactInfo_SocialAccount.Merge(m, src)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_Size() int {
	return xxx_messageInfo_Profile_ContactInfo_SocialAccount.Size(m)
}
func (m *Profile_ContactInfo_SocialAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ContactInfo_SocialAccount.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ContactInfo_SocialAccount proto.InternalMessageInfo

func (m *Profile_ContactInfo_SocialAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Profile_ContactInfo_SocialAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile_ContactInfo_SocialAccount) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type Profile_ProfileStats struct {
	FollowerCount        uint32   `protobuf:"varint,1,opt,name=followerCount,proto3" json:"followerCount,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,2,opt,name=followingCount,proto3" json:"followingCount,omitempty"`
	ListingCount         uint32   `protobuf:"varint,3,opt,name=listingCount,proto3" json:"listingCount,omitempty"`
	RatingCount          uint32   `protobuf:"varint,4,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	PostCount            uint32   `protobuf:"varint,5,opt,name=postCount,proto3" json:"postCount,omitempty"`
	AverageRating        float32  `protobuf:"fixed32,6,opt,name=averageRating,proto3" json:"averageRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ProfileStats) Reset()         { *m = Profile_ProfileStats{} }
func (m *Profile_ProfileStats) String() string { return proto.CompactTextString(m) }
func (*Profile_ProfileStats) ProtoMessage()    {}
func (*Profile_ProfileStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 2}
}

func (m *Profile_ProfileStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ProfileStats.Unmarshal(m, b)
}
func (m *Profile_ProfileStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ProfileStats.Marshal(b, m, deterministic)
}
func (m *Profile_ProfileStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ProfileStats.Merge(m, src)
}
func (m *Profile_ProfileStats) XXX_Size() int {
	return xxx_messageInfo_Profile_ProfileStats.Size(m)
}
func (m *Profile_ProfileStats) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ProfileStats.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ProfileStats proto.InternalMessageInfo

func (m *Profile_ProfileStats) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetListingCount() uint32 {
	if m != nil {
		return m.ListingCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetRatingCount() uint32 {
	if m != nil {
		return m.RatingCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *Profile_ProfileStats) GetAverageRating() float32 {
	if m != nil {
		return m.AverageRating
	}
	return 0
}

// ImageHashes holds image hashes.
type Profile_ImageHashes struct {
	Tiny                 string   `protobuf:"bytes,1,opt,name=tiny,proto3" json:"tiny,omitempty"`
	Small                string   `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	Medium               string   `protobuf:"bytes,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Large                string   `protobuf:"bytes,4,opt,name=large,proto3" json:"large,omitempty"`
	Original             string   `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`
	Filename             string   `protobuf:"bytes,6,opt,name=filename,proto3" json:"filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_ImageHashes) Reset()         { *m = Profile_ImageHashes{} }
func (m *Profile_ImageHashes) String() string { return proto.CompactTextString(m) }
func (*Profile_ImageHashes) ProtoMessage()    {}
func (*Profile_ImageHashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 3}
}

func (m *Profile_ImageHashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ImageHashes.Unmarshal(m, b)
}
func (m *Profile_ImageHashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ImageHashes.Marshal(b, m, deterministic)
}
func (m *Profile_ImageHashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ImageHashes.Merge(m, src)
}
func (m *Profile_ImageHashes) XXX_Size() int {
	return xxx_messageInfo_Profile_ImageHashes.Size(m)
}
func (m *Profile_ImageHashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ImageHashes.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ImageHashes proto.InternalMessageInfo

func (m *Profile_ImageHashes) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

func (m *Profile_ImageHashes) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Profile_ImageHashes) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Profile_ImageHashes) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Profile_ImageHashes) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

func (m *Profile_ImageHashes) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type Profile_ModeratorInfo struct {
	Description          string                              `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	TermsAndConditions   string                              `protobuf:"bytes,2,opt,name=termsAndConditions,proto3" json:"termsAndConditions,omitempty"`
	Languages            []string                            `protobuf:"bytes,3,rep,name=languages,proto3" json:"languages,omitempty"`
	AcceptedCurrencies   []string                            `protobuf:"bytes,4,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"`
	Fee                  *Profile_ModeratorInfo_ModeratorFee `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *Profile_ModeratorInfo) Reset()         { *m = Profile_ModeratorInfo{} }
func (m *Profile_ModeratorInfo) String() string { return proto.CompactTextString(m) }
func (*Profile_ModeratorInfo) ProtoMessage()    {}
func (*Profile_ModeratorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 4}
}

func (m *Profile_ModeratorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ModeratorInfo.Unmarshal(m, b)
}
func (m *Profile_ModeratorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ModeratorInfo.Marshal(b, m, deterministic)
}
func (m *Profile_ModeratorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ModeratorInfo.Merge(m, src)
}
func (m *Profile_ModeratorInfo) XXX_Size() int {
	return xxx_messageInfo_Profile_ModeratorInfo.Size(m)
}
func (m *Profile_ModeratorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ModeratorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ModeratorInfo proto.InternalMessageInfo

func (m *Profile_ModeratorInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Profile_ModeratorInfo) GetTermsAndConditions() string {
	if m != nil {
		return m.TermsAndConditions
	}
	return ""
}

func (m *Profile_ModeratorInfo) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *Profile_ModeratorInfo) GetAcceptedCurrencies() []string {
	if m != nil {
		return m.AcceptedCurrencies
	}
	return nil
}

func (m *Profile_ModeratorInfo) GetFee() *Profile_ModeratorInfo_ModeratorFee {
	if m != nil {
		return m.Fee
	}
	return nil
}

type Profile_ModeratorInfo_ModeratorFee struct {
	FixedFee             *Profile_CurrencyValue                     `protobuf:"bytes,1,opt,name=fixedFee,proto3" json:"fixedFee,omitempty"`
	Percentage           float32                                    `protobuf:"fixed32,2,opt,name=percentage,proto3" json:"percentage,omitempty"`
	FeeType              Profile_ModeratorInfo_ModeratorFee_FeeType `protobuf:"varint,3,opt,name=feeType,proto3,enum=pb.Profile_ModeratorInfo_ModeratorFee_FeeType" json:"feeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *Profile_ModeratorInfo_ModeratorFee) Reset()         { *m = Profile_ModeratorInfo_ModeratorFee{} }
func (m *Profile_ModeratorInfo_ModeratorFee) String() string { return proto.CompactTextString(m) }
func (*Profile_ModeratorInfo_ModeratorFee) ProtoMessage()    {}
func (*Profile_ModeratorInfo_ModeratorFee) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 4, 0}
}

func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Unmarshal(m, b)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Marshal(b, m, deterministic)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Merge(m, src)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_Size() int {
	return xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.Size(m)
}
func (m *Profile_ModeratorInfo_ModeratorFee) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_ModeratorInfo_ModeratorFee proto.InternalMessageInfo

func (m *Profile_ModeratorInfo_ModeratorFee) GetFixedFee() *Profile_CurrencyValue {
	if m != nil {
		return m.FixedFee
	}
	return nil
}

func (m *Profile_ModeratorInfo_ModeratorFee) GetPercentage() float32 {
	if m != nil {
		return m.Percentage
	}
	return 0
}

func (m *Profile_ModeratorInfo_ModeratorFee) GetFeeType() Profile_ModeratorInfo_ModeratorFee_FeeType {
	if m != nil {
		return m.FeeType
	}
	return Profile_ModeratorInfo_ModeratorFee_FixedFee
}

type Profile_Currency struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Divisibility         uint32   `protobuf:"varint,2,opt,name=divisibility,proto3" json:"divisibility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Currency) Reset()         { *m = Profile_Currency{} }
func (m *Profile_Currency) String() string { return proto.CompactTextString(m) }
func (*Profile_Currency) ProtoMessage()    {}
func (*Profile_Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 5}
}

func (m *Profile_Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Currency.Unmarshal(m, b)
}
func (m *Profile_Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Currency.Marshal(b, m, deterministic)
}
func (m *Profile_Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Currency.Merge(m, src)
}
func (m *Profile_Currency) XXX_Size() int {
	return xxx_messageInfo_Profile_Currency.Size(m)
}
func (m *Profile_Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Currency proto.InternalMessageInfo

func (m *Profile_Currency) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Profile_Currency) GetDivisibility() uint32 {
	if m != nil {
		return m.Divisibility
	}
	return 0
}

type Profile_CurrencyValue struct {
	Currency             *Profile_Currency `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               string            `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Profile_CurrencyValue) Reset()         { *m = Profile_CurrencyValue{} }
func (m *Profile_CurrencyValue) String() string { return proto.CompactTextString(m) }
func (*Profile_CurrencyValue) ProtoMessage()    {}
func (*Profile_CurrencyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{8, 6}
}

func (m *Profile_CurrencyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_CurrencyValue.Unmarshal(m, b)
}
func (m *Profile_CurrencyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_CurrencyValue.Marshal(b, m, deterministic)
}
func (m *Profile_CurrencyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_CurrencyValue.Merge(m, src)
}
func (m *Profile_CurrencyValue) XXX_Size() int {
	return xxx_messageInfo_Profile_CurrencyValue.Size(m)
}
func (m *Profile_CurrencyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_CurrencyValue.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_CurrencyValue proto.InternalMessageInfo

func (m *Profile_CurrencyValue) GetCurrency() *Profile_Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

func (m *Profile_CurrencyValue) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.Profile_ModeratorInfo_ModeratorFee_FeeType", Profile_ModeratorInfo_ModeratorFee_FeeType_name, Profile_ModeratorInfo_ModeratorFee_FeeType_value)
	proto.RegisterType((*SubscribeRequest)(nil), "pb.SubscribeRequest")
	proto.RegisterType((*UserData)(nil), "pb.UserData")
	proto.RegisterType((*CrawlNodeRequest)(nil), "pb.CrawlNodeRequest")
	proto.RegisterType((*CrawlNodeResponse)(nil), "pb.CrawlNodeResponse")
	proto.RegisterType((*BanNodeRequest)(nil), "pb.BanNodeRequest")
	proto.RegisterType((*BanNodeResponse)(nil), "pb.BanNodeResponse")
	proto.RegisterType((*UnbanNodeRequest)(nil), "pb.UnbanNodeRequest")
	proto.RegisterType((*UnbanNodeResponse)(nil), "pb.UnbanNodeResponse")
	proto.RegisterType((*Profile)(nil), "pb.Profile")
	proto.RegisterType((*Profile_ProfileColors)(nil), "pb.Profile.ProfileColors")
	proto.RegisterType((*Profile_ContactInfo)(nil), "pb.Profile.ContactInfo")
	proto.RegisterType((*Profile_ContactInfo_SocialAccount)(nil), "pb.Profile.ContactInfo.SocialAccount")
	proto.RegisterType((*Profile_ProfileStats)(nil), "pb.Profile.ProfileStats")
	proto.RegisterType((*Profile_ImageHashes)(nil), "pb.Profile.ImageHashes")
	proto.RegisterType((*Profile_ModeratorInfo)(nil), "pb.Profile.ModeratorInfo")
	proto.RegisterType((*Profile_ModeratorInfo_ModeratorFee)(nil), "pb.Profile.ModeratorInfo.ModeratorFee")
	proto.RegisterType((*Profile_Currency)(nil), "pb.Profile.Currency")
	proto.RegisterType((*Profile_CurrencyValue)(nil), "pb.Profile.CurrencyValue")
}

func init() { proto.RegisterFile("crawler.proto", fileDescriptor_84c7eabcfe7807d1) }

var fileDescriptor_84c7eabcfe7807d1 = []byte{
	// 1207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x5f, 0x6f, 0xdc, 0x44,
	0x10, 0xcf, 0xe5, 0x92, 0xdc, 0xdd, 0xdc, 0x5d, 0x9a, 0x6c, 0x4b, 0x31, 0x16, 0x82, 0xe8, 0x54,
	0x42, 0xd4, 0x07, 0xb7, 0xa4, 0x80, 0xa0, 0x08, 0x50, 0x9b, 0xea, 0xd4, 0x0a, 0x5a, 0x55, 0x4e,
	0x8b, 0xc4, 0xe3, 0xda, 0x9e, 0xf3, 0xad, 0x64, 0x7b, 0xcd, 0xee, 0x3a, 0xe9, 0x7d, 0x07, 0xbe,
	0x02, 0xe2, 0x81, 0x8f, 0x86, 0xc4, 0x23, 0x6f, 0x88, 0x57, 0xb4, 0x7f, 0xec, 0xb3, 0xf3, 0x47,
	0xe1, 0xe9, 0x76, 0x7e, 0xf3, 0xfb, 0xed, 0x8e, 0x67, 0x67, 0xe7, 0x06, 0xa6, 0xb1, 0xa0, 0xe7,
	0x19, 0x8a, 0xa0, 0x14, 0x5c, 0x71, 0xb2, 0x59, 0x46, 0xfe, 0xc7, 0x29, 0xe7, 0x69, 0x86, 0x0f,
	0x0c, 0x12, 0x55, 0x8b, 0x07, 0x8a, 0xe5, 0x28, 0x15, 0xcd, 0x4b, 0x4b, 0xf2, 0xa7, 0x19, 0x93,
	0x8a, 0x15, 0xa9, 0x35, 0x67, 0x04, 0xf6, 0x4e, 0xab, 0x48, 0xc6, 0x82, 0x45, 0x18, 0xe2, 0x2f,
	0x15, 0x4a, 0x35, 0xfb, 0xa3, 0x07, 0xc3, 0xb7, 0x12, 0xc5, 0x33, 0xaa, 0x28, 0xf9, 0x14, 0x06,
	0xa5, 0xe0, 0x0b, 0x96, 0xa1, 0xd7, 0x3b, 0xe8, 0x1d, 0x8d, 0x8f, 0xc7, 0x41, 0x19, 0x05, 0xaf,
	0x2d, 0xf4, 0x7c, 0x23, 0xac, 0xbd, 0xe4, 0x3e, 0x0c, 0xdc, 0xd6, 0xde, 0xa6, 0x21, 0xee, 0x06,
	0xa7, 0x2c, 0x2d, 0x30, 0xf9, 0xd1, 0xa2, 0x9a, 0xeb, 0x08, 0xe4, 0x31, 0x00, 0xbe, 0x2b, 0x99,
	0xa0, 0x8a, 0xf1, 0xc2, 0xeb, 0x1b, 0xba, 0x1f, 0xd8, 0xd0, 0x83, 0x3a, 0xf4, 0xe0, 0x4d, 0x1d,
	0x7a, 0xd8, 0x62, 0x3f, 0xdd, 0x81, 0xad, 0x84, 0x2a, 0x3a, 0x3b, 0x84, 0xbd, 0x13, 0xfd, 0xf9,
	0xaf, 0x78, 0x52, 0x47, 0x4e, 0x08, 0x6c, 0x95, 0x88, 0xc2, 0x44, 0x3a, 0x0a, 0xcd, 0x7a, 0x76,
	0x1b, 0xf6, 0x5b, 0x3c, 0x59, 0xf2, 0x42, 0xe2, 0xec, 0x1e, 0xec, 0x3e, 0xa5, 0xc5, 0x4d, 0xd2,
	0x7d, 0xb8, 0xd5, 0xb0, 0x9c, 0xf0, 0x10, 0xf6, 0xde, 0x16, 0xd1, 0xcd, 0xd2, 0xdb, 0xb0, 0xdf,
	0xe2, 0x39, 0xf1, 0xaf, 0xfb, 0x30, 0x70, 0x99, 0x23, 0x77, 0x61, 0x47, 0x13, 0x5f, 0x3c, 0x73,
	0x32, 0x67, 0xe9, 0xcd, 0x0a, 0x9a, 0xa3, 0xc9, 0xe1, 0x28, 0x34, 0x6b, 0xcd, 0x5d, 0xd2, 0x22,
	0xc9, 0xd0, 0xa4, 0x6a, 0x14, 0x3a, 0x8b, 0xf8, 0x30, 0xcc, 0x78, 0x6c, 0x93, 0xb8, 0x65, 0x3c,
	0x8d, 0x4d, 0xee, 0xc0, 0x36, 0x8d, 0x78, 0xa5, 0xbc, 0x6d, 0xe3, 0xb0, 0x06, 0xb9, 0x0f, 0x7b,
	0x72, 0xc9, 0x85, 0x7a, 0x86, 0xfa, 0xca, 0x4b, 0xa3, 0xdc, 0x31, 0x84, 0x4b, 0xb8, 0x89, 0x44,
	0x2e, 0xce, 0xbd, 0xc1, 0x41, 0xef, 0x68, 0x18, 0x9a, 0xb5, 0x8e, 0xe4, 0x0c, 0x8b, 0x84, 0x0b,
	0x6f, 0x68, 0x50, 0x67, 0x91, 0x0f, 0x61, 0x94, 0xf3, 0x04, 0x05, 0x55, 0x5c, 0x78, 0x23, 0xe3,
	0x5a, 0x03, 0xe4, 0x7b, 0x98, 0x36, 0xc6, 0x8b, 0x62, 0xc1, 0x3d, 0x30, 0x37, 0xfe, 0x41, 0xab,
	0x92, 0x82, 0x97, 0x6d, 0x42, 0xd8, 0xe5, 0x93, 0xaf, 0x61, 0x1c, 0xf3, 0x42, 0xd1, 0x58, 0x19,
	0xf9, 0xd8, 0xc8, 0xdf, 0x6f, 0xcb, 0x4f, 0xd6, 0xee, 0xb0, 0xcd, 0x25, 0x9f, 0xc1, 0x4e, 0xcc,
	0x33, 0x2e, 0xa4, 0x37, 0xb9, 0x7c, 0xa8, 0xfb, 0x3d, 0x31, 0x84, 0xd0, 0x11, 0xc9, 0x37, 0x30,
	0xa1, 0x67, 0x54, 0x51, 0xf1, 0x9c, 0xca, 0x25, 0x4a, 0x6f, 0x7a, 0xf9, 0xb8, 0x17, 0x39, 0x4d,
	0xd1, 0xba, 0xc3, 0x0e, 0x59, 0x8b, 0x97, 0x48, 0x13, 0xac, 0xc5, 0xbb, 0x37, 0x88, 0xdb, 0x64,
	0x12, 0xc0, 0xb6, 0x54, 0x54, 0x49, 0xef, 0x96, 0x51, 0x79, 0x57, 0xc4, 0x7a, 0xaa, 0xfd, 0xa1,
	0xa5, 0xe9, 0xb4, 0x97, 0x55, 0x94, 0xb1, 0xf8, 0x07, 0x5c, 0x79, 0x7b, 0xe6, 0x1e, 0xd7, 0x00,
	0xf9, 0x12, 0xee, 0x4a, 0xc5, 0x05, 0x3e, 0x29, 0x92, 0x39, 0x17, 0xe7, 0x54, 0x24, 0xa7, 0x28,
	0xce, 0x50, 0x48, 0x6f, 0xff, 0xa0, 0x7f, 0x34, 0x0a, 0xaf, 0xf1, 0x92, 0xef, 0x60, 0x92, 0x51,
	0xa9, 0x5e, 0xf2, 0x84, 0x2d, 0x18, 0x26, 0x1e, 0xb9, 0xf1, 0x7d, 0x76, 0xf8, 0xfe, 0xef, 0x3d,
	0x98, 0x76, 0x32, 0x4b, 0x3c, 0xdd, 0x44, 0x58, 0x4e, 0xc5, 0xca, 0x55, 0x7b, 0x6d, 0xea, 0x2f,
	0x90, 0x18, 0xf3, 0x22, 0xd1, 0x3e, 0x5b, 0xf3, 0x6b, 0x40, 0x97, 0xa0, 0xc2, 0x77, 0xca, 0x95,
	0xbd, 0x59, 0x6b, 0xc5, 0x92, 0xa5, 0xcb, 0x8c, 0xa5, 0x4b, 0xe5, 0xaa, 0x7e, 0x0d, 0x90, 0x7b,
	0x30, 0x6d, 0x8c, 0x37, 0x5a, 0x6a, 0xcb, 0xbf, 0x0b, 0xfa, 0xff, 0xf4, 0x60, 0xdc, 0xaa, 0x18,
	0x1d, 0xdf, 0x39, 0x46, 0x92, 0x29, 0xac, 0xe3, 0x73, 0xa6, 0x7e, 0x46, 0x98, 0x53, 0x96, 0xb9,
	0xd8, 0xac, 0x41, 0x0e, 0x60, 0x5c, 0x2e, 0x79, 0x81, 0xaf, 0xaa, 0x3c, 0x42, 0xe1, 0xc2, 0x6b,
	0x43, 0xe4, 0x5b, 0xd8, 0x91, 0x3c, 0x66, 0x34, 0xf3, 0xb6, 0x0e, 0xfa, 0x47, 0xe3, 0xe3, 0x4f,
	0xae, 0x29, 0xd6, 0xe0, 0xd4, 0xb0, 0x9e, 0xc4, 0x31, 0xaf, 0x0a, 0x15, 0x3a, 0x91, 0xff, 0x16,
	0xa6, 0x1d, 0x87, 0xc9, 0xc4, 0xaa, 0xac, 0xc3, 0x33, 0x6b, 0xfd, 0xfc, 0x2b, 0x89, 0xa2, 0xd5,
	0x2e, 0x1a, 0x5b, 0xc7, 0x5d, 0x0a, 0xce, 0x17, 0x2e, 0x36, 0x6b, 0xf8, 0x7f, 0xf5, 0x60, 0xd2,
	0xae, 0x23, 0x9d, 0xae, 0x05, 0xcf, 0x32, 0x7e, 0x8e, 0xe2, 0x44, 0x9f, 0x63, 0xf6, 0x9f, 0x86,
	0x5d, 0x90, 0x1c, 0xc2, 0xae, 0x05, 0x58, 0x91, 0x5a, 0xda, 0xa6, 0xa1, 0x5d, 0x40, 0xc9, 0x0c,
	0x26, 0xae, 0xc3, 0x5b, 0x56, 0xdf, 0xb0, 0x3a, 0x98, 0x4e, 0x9d, 0x6e, 0xe4, 0x35, 0x65, 0xcb,
	0x50, 0xda, 0x90, 0x29, 0x6a, 0x2e, 0x95, 0xf5, 0x6f, 0x1b, 0xff, 0x1a, 0xd0, 0x11, 0xd3, 0x33,
	0x14, 0x34, 0xc5, 0xd0, 0x68, 0x4c, 0xfb, 0xda, 0x0c, 0xbb, 0xa0, 0xff, 0x5b, 0x0f, 0xc6, 0xad,
	0x67, 0x66, 0xd2, 0xc7, 0x8a, 0x55, 0x93, 0x3e, 0x56, 0xac, 0x74, 0x8a, 0x64, 0x4e, 0xb3, 0xe6,
	0x6a, 0x8d, 0xa1, 0x3b, 0x5c, 0x8e, 0x09, 0xab, 0xf2, 0xba, 0xd7, 0x5a, 0x4b, 0xb3, 0x33, 0x2a,
	0x52, 0x74, 0x25, 0x67, 0x0d, 0x7d, 0x05, 0x5c, 0xb0, 0x94, 0x15, 0x34, 0x73, 0x95, 0xd6, 0xd8,
	0xda, 0xa7, 0x13, 0x6d, 0xae, 0xc7, 0xf6, 0xd8, 0xc6, 0xf6, 0xff, 0xec, 0xc3, 0xb4, 0xd3, 0xf1,
	0x74, 0x5e, 0x92, 0x56, 0x53, 0xb6, 0x81, 0xb6, 0x21, 0x12, 0x00, 0x51, 0x28, 0x72, 0xf9, 0xa4,
	0x48, 0x4e, 0x78, 0x91, 0x30, 0x0d, 0x4a, 0x17, 0xfc, 0x15, 0x1e, 0x9d, 0xc7, 0x8c, 0x16, 0x69,
	0x45, 0x53, 0x94, 0x5e, 0xdf, 0xbc, 0xf8, 0x35, 0xa0, 0x77, 0xa3, 0x71, 0x8c, 0xa5, 0xc2, 0xe4,
	0xa4, 0x12, 0x02, 0x8b, 0x98, 0xa1, 0x34, 0xc5, 0x3a, 0x0a, 0xaf, 0xf0, 0x90, 0xaf, 0xa0, 0xbf,
	0x40, 0x34, 0x1f, 0x39, 0x3e, 0x3e, 0xbc, 0xb6, 0x73, 0xaf, 0xad, 0x39, 0x62, 0xa8, 0x25, 0xfe,
	0xbf, 0x3d, 0x98, 0xb4, 0x51, 0xf2, 0x85, 0x4e, 0xcc, 0x3b, 0x4c, 0xe6, 0x58, 0xcf, 0x14, 0x9d,
	0xa6, 0xec, 0x0e, 0x5d, 0xfd, 0x44, 0xb3, 0x0a, 0xc3, 0x86, 0x4a, 0x3e, 0x02, 0x28, 0x51, 0xc4,
	0x58, 0x28, 0x9a, 0xda, 0x82, 0xdf, 0x0c, 0x5b, 0x08, 0x79, 0x0e, 0x83, 0x05, 0xe2, 0x1b, 0xfd,
	0x4a, 0xf4, 0xd5, 0xed, 0x1e, 0x07, 0xff, 0x2f, 0xca, 0x60, 0x6e, 0x55, 0x61, 0x2d, 0x9f, 0xcd,
	0x61, 0xe0, 0x30, 0x32, 0x81, 0xe1, 0xdc, 0x05, 0xb0, 0xb7, 0x41, 0xf6, 0x61, 0xfa, 0xba, 0x39,
	0x50, 0x43, 0x3d, 0xe2, 0xc3, 0x5d, 0x43, 0x78, 0x9d, 0x55, 0xb2, 0xeb, 0xdb, 0xf4, 0x9f, 0xc2,
	0xb0, 0xfe, 0x18, 0x5d, 0x81, 0x31, 0x4f, 0x9a, 0x07, 0xac, 0xd7, 0xfa, 0xbd, 0x24, 0xec, 0x8c,
	0x49, 0x16, 0xb1, 0x8c, 0xa9, 0x95, 0x7b, 0x55, 0x1d, 0xcc, 0xff, 0x19, 0xa6, 0x9d, 0x84, 0x90,
	0x87, 0x30, 0x8c, 0x1d, 0xe0, 0xb2, 0x77, 0xe7, 0xaa, 0xec, 0x85, 0x0d, 0x4b, 0x97, 0x34, 0xcd,
	0x9b, 0x67, 0x3b, 0x0a, 0x9d, 0x75, 0xfc, 0x77, 0x0f, 0x46, 0x3c, 0x72, 0x33, 0x24, 0x79, 0x04,
	0xa3, 0x66, 0x12, 0x24, 0x66, 0xcb, 0x8b, 0x83, 0xa1, 0x3f, 0xd1, 0x68, 0x3d, 0x19, 0xce, 0x36,
	0x1e, 0xf6, 0xc8, 0x63, 0x18, 0x35, 0xc3, 0x95, 0x15, 0x5d, 0x9c, 0xc9, 0xfc, 0xf7, 0x2e, 0xa0,
	0x6e, 0x16, 0xda, 0x20, 0x9f, 0xc3, 0xc0, 0x4d, 0x57, 0x84, 0x68, 0x4e, 0x77, 0x20, 0xf3, 0x6f,
	0x77, 0xb0, 0x46, 0xf5, 0x18, 0x46, 0xcd, 0x60, 0x65, 0x4f, 0xbc, 0x38, 0x8f, 0xd9, 0x13, 0x2f,
	0x4f, 0x5f, 0x1b, 0xd1, 0x8e, 0xf9, 0xeb, 0x7a, 0xf4, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x90,
	0x7c, 0xe3, 0xfe, 0x38, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObcrawlerClient is the client API for Obcrawler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObcrawlerClient interface {
	// Subscribe is an RPC which streams new profiles and listings as they
	// are crawled. Note you should subscribe to this as soon as the crawler
	// starts as any data that is crawled while not subscribed will not be
	// resent until the node is crawled again.
	//
	// Also, search engines MUST respect the expiration and not return any
	// data which has expired.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Obcrawler_SubscribeClient, error)
	// CrawlNode queues up a crawl of the given node.
	CrawlNode(ctx context.Context, in *CrawlNodeRequest, opts ...grpc.CallOption) (*CrawlNodeResponse, error)
	// BanNode will prevent the node from being crawled in the future as
	// well as purge all cached/pinned files of this node from the crawler.
	BanNode(ctx context.Context, in *BanNodeRequest, opts ...grpc.CallOption) (*BanNodeResponse, error)
	// UnbanNode will un-ban the provided node. It will not immediately
	// crawl the node again. If you want that call CrawlNode.
	UnbanNode(ctx context.Context, in *UnbanNodeRequest, opts ...grpc.CallOption) (*UnbanNodeResponse, error)
}

type obcrawlerClient struct {
	cc *grpc.ClientConn
}

func NewObcrawlerClient(cc *grpc.ClientConn) ObcrawlerClient {
	return &obcrawlerClient{cc}
}

func (c *obcrawlerClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Obcrawler_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Obcrawler_serviceDesc.Streams[0], "/pb.obcrawler/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &obcrawlerSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Obcrawler_SubscribeClient interface {
	Recv() (*UserData, error)
	grpc.ClientStream
}

type obcrawlerSubscribeClient struct {
	grpc.ClientStream
}

func (x *obcrawlerSubscribeClient) Recv() (*UserData, error) {
	m := new(UserData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *obcrawlerClient) CrawlNode(ctx context.Context, in *CrawlNodeRequest, opts ...grpc.CallOption) (*CrawlNodeResponse, error) {
	out := new(CrawlNodeResponse)
	err := c.cc.Invoke(ctx, "/pb.obcrawler/CrawlNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obcrawlerClient) BanNode(ctx context.Context, in *BanNodeRequest, opts ...grpc.CallOption) (*BanNodeResponse, error) {
	out := new(BanNodeResponse)
	err := c.cc.Invoke(ctx, "/pb.obcrawler/BanNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *obcrawlerClient) UnbanNode(ctx context.Context, in *UnbanNodeRequest, opts ...grpc.CallOption) (*UnbanNodeResponse, error) {
	out := new(UnbanNodeResponse)
	err := c.cc.Invoke(ctx, "/pb.obcrawler/UnbanNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObcrawlerServer is the server API for Obcrawler service.
type ObcrawlerServer interface {
	// Subscribe is an RPC which streams new profiles and listings as they
	// are crawled. Note you should subscribe to this as soon as the crawler
	// starts as any data that is crawled while not subscribed will not be
	// resent until the node is crawled again.
	//
	// Also, search engines MUST respect the expiration and not return any
	// data which has expired.
	Subscribe(*SubscribeRequest, Obcrawler_SubscribeServer) error
	// CrawlNode queues up a crawl of the given node.
	CrawlNode(context.Context, *CrawlNodeRequest) (*CrawlNodeResponse, error)
	// BanNode will prevent the node from being crawled in the future as
	// well as purge all cached/pinned files of this node from the crawler.
	BanNode(context.Context, *BanNodeRequest) (*BanNodeResponse, error)
	// UnbanNode will un-ban the provided node. It will not immediately
	// crawl the node again. If you want that call CrawlNode.
	UnbanNode(context.Context, *UnbanNodeRequest) (*UnbanNodeResponse, error)
}

// UnimplementedObcrawlerServer can be embedded to have forward compatible implementations.
type UnimplementedObcrawlerServer struct {
}

func (*UnimplementedObcrawlerServer) Subscribe(req *SubscribeRequest, srv Obcrawler_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedObcrawlerServer) CrawlNode(ctx context.Context, req *CrawlNodeRequest) (*CrawlNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CrawlNode not implemented")
}
func (*UnimplementedObcrawlerServer) BanNode(ctx context.Context, req *BanNodeRequest) (*BanNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BanNode not implemented")
}
func (*UnimplementedObcrawlerServer) UnbanNode(ctx context.Context, req *UnbanNodeRequest) (*UnbanNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbanNode not implemented")
}

func RegisterObcrawlerServer(s *grpc.Server, srv ObcrawlerServer) {
	s.RegisterService(&_Obcrawler_serviceDesc, srv)
}

func _Obcrawler_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ObcrawlerServer).Subscribe(m, &obcrawlerSubscribeServer{stream})
}

type Obcrawler_SubscribeServer interface {
	Send(*UserData) error
	grpc.ServerStream
}

type obcrawlerSubscribeServer struct {
	grpc.ServerStream
}

func (x *obcrawlerSubscribeServer) Send(m *UserData) error {
	return x.ServerStream.SendMsg(m)
}

func _Obcrawler_CrawlNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrawlNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObcrawlerServer).CrawlNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.obcrawler/CrawlNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObcrawlerServer).CrawlNode(ctx, req.(*CrawlNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obcrawler_BanNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObcrawlerServer).BanNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.obcrawler/BanNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObcrawlerServer).BanNode(ctx, req.(*BanNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Obcrawler_UnbanNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObcrawlerServer).UnbanNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.obcrawler/UnbanNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObcrawlerServer).UnbanNode(ctx, req.(*UnbanNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Obcrawler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.obcrawler",
	HandlerType: (*ObcrawlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrawlNode",
			Handler:    _Obcrawler_CrawlNode_Handler,
		},
		{
			MethodName: "BanNode",
			Handler:    _Obcrawler_BanNode_Handler,
		},
		{
			MethodName: "UnbanNode",
			Handler:    _Obcrawler_UnbanNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Obcrawler_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "crawler.proto",
}
